### ISSUE TITLE
没越狱的不能用吗

### ISSUE THREAD

**Issue by luohancfd** [kayanouriko/E-HentaiViewer#1]
谢谢大佬开发。。不过这个只能越狱的用是吗。。

**Comment by kayanouriko** [comment]
https://github.com/DaidoujiChen/Dai-Hentai/issues/64 
可以使用这里的方法,原理应该是用自己的账号创建一个时限一周的临时调试证书从而使应用安装在自己机子上
同时推荐先使用Dai-Hentai应用,我的应用功能太比较薄弱,而且详情页请求逻辑太渣了日常浏览使用不是很爽
新年快乐~
