### ISSUE TITLE
新的1.0.5版本在5s中无法加载图片？

### ISSUE THREAD

**Issue by YLaido** [kayanouriko/E-HentaiViewer#10]
先感谢一下开发者dalao，界面很清新，tag和评论这些核心功能都做出来了，而且还有里区支持 :tada: 
说下遇到的问题：
Platform:  5s    ios 9.2.1 
尝试过VMware的macOS下xcode编译和CydiaImpactor两种方式安装都发现点击"阅读"后都是空白页面，等了2-3min也没加载出东西来，而且拖到十几页后按回退的话，程序会crash。换了多个梯子也是一样的情况。。
最后不知能否说点愿望？希望dalao能实现像EHviewer那样，点击tag后是自动填充到搜索栏中，这样自己也可以添加其他keyword

**Comment by kayanouriko** [comment]
风格修改只是个人技术太渣,怕对同风格安卓应用的用户造成误解,避嫌还是重改风格了..老版也有里站功能的就在首页正上方切换

我也是长期用自己的手机和pad使用这应用,暂没重现你的崩溃描述..如果可以你可以按照下面的方法把crash文件给我分析一下
你可以参照网络上的方法把Crash文件给我,看到你也用Xcode,可以链接上你的手机,在Xcode-Windows-devices 选中自己的手机,右侧view log,找到Crash文件给我

这应用说白了还是半残品,要修改的地方也很多,小毛病也很多,我也在努力的提升自己的技术让这应用变得更好,我编写的周期会很长很长,抱歉啦,你可以期待一下有更好的iOS的EH应用~

感恩~

**Comment by YLaido** [comment]
[Logs](https://drive.google.com/file/d/0B06SMIWr51yQSGdlSnN2RDdJV3c/view)在这里 :smile: 
我现在在用老版本的，感觉功能要再完善一点就好了(比如滚动加载之类的),有的本子也只能加载个30页左右，真是莫大的sad。。 :sob: 
Anyway，有APP就很满足了，继续期待您的新版本 :taco:

**Comment by kayanouriko** [comment]
看来是浏览器控件的问题,现在这个浏览器控件还得改的说
等我做完A岛的娱乐项目在重新弄这个吧

**Comment by YLaido** [comment]
好的，麻烦dalao了,take your time :smile:

**Comment by lioliy** [comment]
似乎不兼容iOS 9，所有图片都无法加载，我的所有iOS9设备也是

**Comment by kayanouriko** [comment]
@lioliy 你好,用浏览器打开站点可以浏览不?
单图片无法加载很大原因在于你用的网络工具ip太多人用了导致509错误,被识别为爬虫行为,这种错误我还没单独剥离出来..

**Comment by NanerLee** [comment]
ip8 ios11.3 1.11版本阅读模式下也看不到图片，其他到是正常

在阅读模式下，加载条完成之后，就是一片空白，如果长按选择刷新会看到图片一点一点显示出来，但是刷新完成之后又是一片空白

**Comment by kayanouriko** [comment]
@NanerLee 
我这边模拟器测试正常,残念,你更换一下梯子姿势看是不是梯子的问题
目前正在改造看图浏览器,抛弃这种内嵌webView加载图片的方式
假期会修改完成,到时候你再试试新的浏览方式看看效果吧,抱歉了

**Comment by NanerLee** [comment]
@kayanouriko 嗯，我去找个别的梯子试试，但我感觉应该不是网络的问题，毕竟图片能看到一瞬间，说明图片应该是下载下来了，只是显示上出了问题。

很期待新的浏览方式，说实话能够有ios的App就已经很开心了，还是要感觉一下开发者

**Comment by xioxin** [comment]
webView 内的情况可以用Safari 调试
