### ISSUE TITLE
收藏刷新时报错

### ISSUE THREAD

**Issue by hnboy2005** [kayanouriko/E-HentaiViewer#11]
![image](https://user-images.githubusercontent.com/3166227/29203574-7f85ec0c-7ea4-11e7-8c48-97eaf718c1ea.png)

**Comment by kayanouriko** [comment]
收藏我还没改完,偷懒在master上提交了...
目前登陆完账号第一次加载必定会走这个提示,第二次刷新就不会了...
而已默认加载全部文件夹的第一页,不会也不能自动加载第二页,切换到收藏页面没有登录提示

如果你第二次刷新也出现这提示,我这边真没法复现这问题了,不介意的话把你的账号邮箱给我测试一下,我来看看是不是你的收藏夹解析问题

感恩~

**Comment by hnboy2005** [comment]
我这里收藏页签多次刷新同样会报这个错.
邮箱账号密码 发送到你的163邮箱了. 谢谢大神.

**Comment by kayanouriko** [comment]
记录:收藏夹每页50条数据,e站的api并不支持一次性获取那么多数据导致的bug

**Comment by kayanouriko** [comment]
新版已经修复这个bug了
