### ISSUE TITLE
[Bug] iPhone X支持以及预览无法加载问题

### ISSUE THREAD

**Issue by misaka10086** [kayanouriko/E-HentaiViewer#14]
你好,请问是否考虑修改SafeArea以支持iPhone X全屏,目前版本在iPhone X运行时status bar布局不正确同时预览无法工作,直接显示空白. 非常感谢

测试环境:iPhone X, iOS 11.1, Xcode 9.1

**Comment by kayanouriko** [comment]
土豪粗线!
最近公司业务较忙,一直没时间更新
这个月应该会有一次更新,适配X和添加完整的搜索功能(同步官网)和更实用的搜索界面
感谢感谢~

**Comment by xioxin** [comment]
![5ae75db1-5cc1-49b0-9f08-6035eb8caef5](https://user-images.githubusercontent.com/5716100/33359890-0fdba8f6-d50c-11e7-9dcc-0f76f20ea82b.png)

X 下 点不到关闭按键 翻页进度条也和home条冲突

**Comment by kayanouriko** [comment]
![](https://ws3.sinaimg.cn/large/006tNc79gy1flzcfk6e8fj30yi1pc7wi.jpg)

最近是真的忙,这个月要鸽了赶脚

**Comment by kayanouriko** [comment]
已更新
