### ISSUE TITLE
如何安装这类ipa？

### ISSUE THREAD

**Issue by aiyce** [kayanouriko/E-HentaiViewer#16]
小白，求教！

**Comment by aiyce** [comment]
百度了一波，是要申请开发者账号99刀一年才能安装吗？
用那个xcode吗？
。。。
突然想放弃了。。。
这个可以分享网页安装吗？
留个邮箱给 如果能共享的话
wuaiyce@gmail.com

**Comment by aiyce** [comment]
申请完开发者账号
正准备下载xcode 发现没有windows版。。。
希望哪位好心人能发一个开发者版的链接。。。

**Comment by codexss** [comment]
https://medium.com/@Lentin/不越狱安装ipa的方法-10e40344f987

**Comment by kayanouriko** [comment]
https://github.com/kayanouriko/E-HentaiViewer/issues/1
