### ISSUE TITLE
AppDelegate 第52行写错了

### ISSUE THREAD

**Issue by chenlx761** [kayanouriko/E-HentaiViewer#17]
TagCnMode写成了ProtectMode

**Comment by chenlx761** [comment]
还有,我可以请教一下,您的内置翻墙是怎么弄的吗?

**Comment by kaiwwww** [comment]
我记得exhentai无需翻墙？我这里是可以不开ss裸进的。

chenmingdu <notifications@github.com> 于 2017年12月12日周二 上午10:18写道：

**Comment by kayanouriko** [comment]
哈哈,解决了另外一个issue的问题,是我马大哈了,而且不能这样判断的说
分地区的吧,我这里没被墙,也没开,果连的..

**Comment by chenlx761** [comment]
哈哈 我也不知道能不能这么判断 刚刚开始android转ios 看到这个项目 就下载下来研究研究了
