### ISSUE TITLE
[建议]增加分享链接功能

### ISSUE THREAD

**Issue by xioxin** [kayanouriko/E-HentaiViewer#18]
想快速分享网页 或者通过airdrop发送到电脑

当然如果能支持Handoff那就最好了

**Comment by kayanouriko** [comment]
这个分享本身就是计划中的Extesions部分功能
ShareExtesions的分享,分享封面和链接到支持的应用,还会实现Safari或workflow直接跳转应用的画廊详情
还有TodayExtesions的小部件
Handoff估计是不行了,这个涉及特殊权限,不知道没上架的应用是否有效
野心虽大,但是好多基础功能都要改进的现实

**Comment by Kennnnnnji** [comment]
新年快乐！发现这个app 真是十分开心，希望能坚持更新！感谢大佬👍
