### ISSUE TITLE
IPX ios11.2.1 出现解析错误 请升级版本的提示  但是重新安装新版本后并没有什么卵用

### ISSUE THREAD

**Issue by ariosnaga** [kayanouriko/E-HentaiViewer#19]

**Comment by kayanouriko** [comment]
你好,是哪个页面提示这个?

**Comment by ariosnaga** [comment]
![img_0172](https://user-images.githubusercontent.com/34322316/34570203-5bc10b6e-f16b-11e7-8c4f-14dc29ff362d.PNG)
![img_0173](https://user-images.githubusercontent.com/34322316/34570205-5bd892a2-f16b-11e7-81a3-ffe5e3b9fca7.PNG)
![img_0174](https://user-images.githubusercontent.com/34322316/34570206-5bf543d4-f16b-11e7-8d3e-83b103a58ed8.PNG)
几乎每个页面都有这个问题

**Comment by kayanouriko** [comment]
浏览器能打开网站么?尝试一下vpn试试看
我还没细分出网站的各种状态码,你这种应该是没解析到数据

**Comment by ariosnaga** [comment]
浏览器能正常打开，不过我现在人在欧洲，不知是不是也有关系

**Comment by ariosnaga** [comment]
啊，挂了别的国家的VPN可以用了，真实怪事情，谢谢啦:D
