### ISSUE TITLE
網址有更新囉

### ISSUE THREAD

**Issue by DaidoujiChen** [kayanouriko/E-HentaiViewer#2]
Hello @kayanouriko,

在 [HentaiParser.m](https://github.com/kayanouriko/E-HentaiViewer/blob/master/ExReadViewer/HentaiParser.m#L13-L14) 的網址可以換成

`````
https://e-hentai.org/api.php
https://exhentai.org/api.php
`````

囉

**Comment by kayanouriko** [comment]
嗯,前阵子过年在家的时候就知道改动了,github上一直没更新,怠惰ですね...
新春快乐撒~
