### ISSUE TITLE
我用 Dai-hentai 的 Windows 安装方法始终装不上 是不是失效了呢？可以大概说明下可行的方法吗：）

### ISSUE THREAD

**Issue by Corazonnnn** [kayanouriko/E-HentaiViewer#20]

**Comment by stu43005** [comment]
**TL;DR**: 我用那方法裝的，可行。

基本上安裝步驟就如他的說明說的做就行了，安裝後iPhone上出現``E-H``表示成功了，
不過Dai-hentai那邊少了一個步驟：
- 到「設定」>「一般」>「描述檔」內，點選開發者APP（Email顯示你的Apple ID）進入，點擊「信任」，會跳出詢問窗口再次點擊「信任」。
- 如無法信任憑證，請確認網路是否正常，依舊不行請移除越獄APP重裝一次。
![image](https://user-images.githubusercontent.com/1288549/34826268-dc997afa-f710-11e7-928d-ad3ef7bde5ca.png)

另外如果Cydia Impactor過程中出現錯誤訊息，可以參考下面的資訊：
- 過程中如果跳出「``Apple Developer Warning``」提示窗點選「``OK``」繼續就好
- 過程中也許可能會跳出「``plist.hpp:201``」錯誤，不需理會點下「``確定``」依舊可安裝
- 如跳出「``provision.cpp:62``」錯誤，可參考[這篇](https://mrmad.com.tw/provision-cpp-62)來解決。
- 如跳出「``provision.cpp:81``」錯誤，可參考[這篇](https://mrmad.com.tw/provision-cpp81-error)來解決。
- 如跳出「``http-win.cpp:158``」錯誤，可參考[這篇](https://mrmad.com.tw/cydia-impactor-http-win-cpp158)來解決。
- 如跳出「``provision.cpp:168`` or ``150``」錯誤，請關閉Apple ID雙重認證，或次另註冊一組新的Apple ID來使用。

**Comment by Corazonnnn** [comment]
*{
        margin: 0;
        padding: 0;
    }
    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
感谢！已经解决了，我的问题是 ID 双重认证的原因，另外注册一个就好啦！不过 7 天有效期确实不爽，所以我想再请教下 Dai-hentai 所说的原生 XCode 的安装方法，我用 Macbook Pro 试过中途很多步骤不是很清楚，你有更详细的操作步骤吗？再次感谢！：）



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.5;
        }
    
发自 Corazon

                


    在2018年1月11日 20:52，Shiaupiau<notifications@github.com> 写道： 


TL;DR: 我用那方法裝的，可行。
基本上安裝步驟就如他的說明說的做就行了，安裝後iPhone上出現E-H表示成功了，
不過Dai-hentai那邊少了一個步驟：

到「設定」>「一般」>「描述檔」內，點選開發者APP（Email顯示你的Apple ID）進入，點擊「信任」，會跳出詢問窗口再次點擊「信任」。
如無法信任憑證，請確認網路是否正常，依舊不行請移除越獄APP重裝一次。


另外如果Cydia Impactor過程中出現錯誤訊息，可以參考下面的資訊：

過程中如果跳出「Apple Developer Warning」提示窗點選「OK」繼續就好
過程中也許可能會跳出「plist.hpp:201」錯誤，不需理會點下「確定」依舊可安裝
如跳出「provision.cpp:62」錯誤，可參考這篇來解決。
如跳出「provision.cpp:81」錯誤，可參考這篇來解決。
如跳出「http-win.cpp:158」錯誤，可參考這篇來解決。
如跳出「provision.cpp:168 or 150」錯誤，請關閉Apple ID雙重認證，或次另註冊一組新的Apple ID來使用。

**Comment by stu43005** [comment]
Cydia Impactor做的事情就是幫你的帳號開通開發者功能，
因為是使用免費的開發者帳號，所以不管你是用Cydia Impactor還是用Xcode安裝都一樣會有7天限制（描述檔到期）。

**Comment by kayanouriko** [comment]
1. 配置里面设置你的apple ID
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fnh03ib5j9j30x00jq7ah.jpg)

2. 在如图地方修改为你的账号,xcode会自动帮你生成对应的证书
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fnh03i7ktjj31kw0ikdlm.jpg)

3. 如图地方改为release
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fnh03i15rfj309u04w74o.jpg)
![](https://ws3.sinaimg.cn/large/006tKfTcgy1fnh03hx92cj317w096taf.jpg)

4. 链接你的手机,开始编译 enjoy!
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fnh03hs9bjj30cq07et9n.jpg)

**Comment by frost134** [comment]
我也是爬完这里和Dai hentai的readme就会装了。和大家说的都一样。不过
1、我自己不是开发者账户也能装
2、要自己修改Bundle identifier（不然run会报错）

**Comment by Vrinan** [comment]
```
第一个怎么“No description provided.”
请问怎么安装=-=
```

**Comment by inorysora** [comment]
= =按照教程弄到最run的时候Build Failed了，提示YYwebimage.h file not found

**Comment by errorfg** [comment]
报can not register tw.daidouji.hentai的话，就到
![image](https://user-images.githubusercontent.com/18473413/65699716-10f78180-e0b1-11e9-8438-78b9991fb795.png)
更改Bundle Identifier即可
