### ISSUE TITLE
Can not show thumbnail and the photo

### ISSUE THREAD

**Issue by simonlkch** [kayanouriko/E-HentaiViewer#21]
iphone 6 plus, ios 9

the application show the book cover only, my device can not show any thumbnail and comic.

also when i click the top list, the application will CTD

**Comment by kayanouriko** [comment]
Please try to using VPN
Toplist wait for repair

**Comment by simonlkch** [comment]
Tks for reply, I am not in China. Maybe I think that was The IOS 9 problem

**Comment by kayanouriko** [comment]
I test in the iOS9.0 simulator, the application works fine.So sad

https://github.com/kayanouriko/E-HentaiViewer/issues/19#issuecomment-355315621
He's in Europe, but he's working fine after hanging up the VPN
