### ISSUE TITLE
可以增加横版阅读的功能么？

### ISSUE THREAD

**Issue by zhouhongyu9310** [kayanouriko/E-HentaiViewer#22]
一直习惯使用横版阅读了，纵版的字很小，看的比较难受

Thanks

**Comment by kayanouriko** [comment]
已经在计划中,这个涉及看图浏览器部分,我想在重构更好的看图浏览器后再添加该特性
对于横版有需求的可以去隔壁的daidoujichen的应用尝试一下哦~
https://github.com/kayanouriko/E-HentaiViewer/issues/12
