### ISSUE TITLE
网页登录上去了EX还是无法显示

### ISSUE THREAD

**Issue by damien00** [kayanouriko/E-HentaiViewer#23]
Safari的数据都清空了 先登录上去后 EX还是熊猫。软件显示：解析错误 等待升级版本（应该还是熊猫的锅）
系统ios11.0
大佬有没有解决办法T-T 或者是我操作步骤有问题

**Comment by kayanouriko** [comment]
这你还是换个VPN试试,我这一块没太深入,基本套用iOS自带的cookie管理...无能为力了sad

**Comment by damien00** [comment]
![image](https://user-images.githubusercontent.com/24964202/36812185-3e342a24-1d0b-11e8-9417-03537a43e92b.png)
![image](https://user-images.githubusercontent.com/24964202/36812195-44cd5ab8-1d0b-11e8-8a44-ef87b6bf2861.png)
换了手机EX还是进不去 而且有bug，切换到EX后，在当前热门一点阅读就会闪退
看能不能加入个cookie登录的功能呢~

**Comment by kayanouriko** [comment]
挂个梯子试试吧

**Comment by damien00** [comment]
emmm 挂了霓虹梯子的， 梯子速度也挺快的

**Comment by kayanouriko** [comment]
参照这里,也有可能是梯子的锅:https://github.com/kayanouriko/E-HentaiViewer/issues/19#issuecomment-355315621
或者是账号的锅
如果不行的话那我只能摊手了sad
cookie原理我开始的时候没理解通透,所以后来就直接放弃这种方式登陆了

**Comment by damien00** [comment]
ip可以打开ex了（裸连的）希望有左手模式啊
但是我一直在用的安卓备用机的eh打不开ex了（不同的号）emmn 难道同一ip下只能使用一个账号吗？
