### ISSUE TITLE
考虑加入自动翻页功能吗

### ISSUE THREAD

**Issue by pipiTan** [kayanouriko/E-HentaiViewer#24]
就是酱紫。

**Comment by kayanouriko** [comment]
你好,关于看图部分的新增功能,包括横屏浏览,翻页方式,书签等
在重构更好的看图浏览器后再添加这些特性
现在的看图浏览器太渣了

**Comment by kayanouriko** [comment]
思考了一下，暂时不加入自动翻页功能了
新界面加入了两个屏幕方式和滚动方式，应该足够日常使用了
