### ISSUE TITLE
未越狱iOS11可以使用么

### ISSUE THREAD

**Issue by hakula1125** [kayanouriko/E-HentaiViewer#25]
小白提问。。请问未越狱机器可以下载使用不？我在release里下载的ipa不能直接安装，请问是通过其他渠道的么？谢谢

**Comment by kayanouriko** [comment]
参照: https://github.com/kayanouriko/E-HentaiViewer/issues/20#issuecomment-356925389

**Comment by zlq4863947** [comment]
@kayanouriko 去淘宝花10rmb 把ipa注册成企业证书 就不用xcode那种安装方式了

**Comment by kayanouriko** [comment]
@zlq4863947 其实这应用还是自用为主,这应用也没做任何推广
前阵子出了亚洲锁IP的事情,还是不要那么张扬的好
喜欢折腾或者钻研的人如果对这项目看得上眼自己会知道怎么弄的吧

**Comment by zlq4863947** [comment]
@kayanouriko 嗯 话说你有用过swift吗 我最近在学习ios 只会用swift 你这个objective-c，我看着有点费劲。。。 感觉还是swift好懂。。。

**Comment by kayanouriko** [comment]
@zlq4863947 不用拿我的项目学iOS啦,代码太烂了
隔壁daihentaitai有swift版的登陆逻辑的说

**Comment by mittwillson** [comment]
@zlq4863947 10rmb的是个人证书 绑机器的，企业证书一个月要500多块钱，而且通常不会签这种类型的app

**Comment by zlq4863947** [comment]
@MittWillson 我说淘宝，让有企业证书的店家帮忙 标记一下 好像是10元，
500那个 你说的是正规渠道吧

**Comment by zlq4863947** [comment]
@kayanouriko 隔壁daihentaitai 能发个传送门不？

**Comment by mittwillson** [comment]
@zlq4863947 淘宝那种就是这样啊 10块钱标记你UUID的那个是个人开发者  企业证书是不需要标记你设备的，淘宝企业证书都是产业链专门给棋牌游戏签名的，一年的费用比申请企业开发者费用高十几倍

**Comment by kayanouriko** [comment]
@MittWillson 淘宝不知道，但是蒲公英平台也有企业证书服务，每月60块左右
@zlq4863947 看README有传送门

**Comment by zlq4863947** [comment]
@MittWillson 这么贵呀，个人开发者 我也有账号 不需要他那个，
我是想如果能绕过appstore，10元钱不贵，一个月500 就太贵了 接受不了

**Comment by zlq4863947** [comment]
@kayanouriko 好的，有qq群没有？一起交流开发经验啥的。。
