### ISSUE TITLE
[建议]两点建议

### ISSUE THREAD

**Issue by Blackssugar** [kayanouriko/E-HentaiViewer#26]
第一个是能不能加入卷轴浏览模式这样可以快速翻页而且感觉更连贯
第二个是点击图片两侧跳页的时候可不可取消划动的动画直接闪现下一页或上一页这样感觉更方便一些

**Comment by Blackssugar** [comment]
还有点击toplist就会闪退

**Comment by kayanouriko** [comment]
关于看图浏览器部分的新增特性,参照:https://github.com/kayanouriko/E-HentaiViewer/issues/24#issuecomment-361552814

toplist尚未开发完成,当时打包的时候忘记屏蔽了,sad

**Comment by Blackssugar** [comment]
还有图廊要是有跳页功能就好啦 :)

**Comment by Blackssugar** [comment]
打开指纹锁以后 返回过桌面后 再打开任务管理器显示这个app的浏览图能不能改成 显示需要解锁之类的图片  类似 1Password 这个app的效果

**Comment by Blackssugar** [comment]
打开指纹锁以后 打开app的时候能不能也加入指纹解锁 还有就是返回过桌面后 再打开任务管理器显示这个app的浏览图能不能改成 显示需要解锁之类的图片 类似 1Password 这个app的效果

**Comment by Blackssugar** [comment]
打开指纹锁以后 返回过系统桌面后 再打开任务管理器显示这个app的浏览图能不能改成 显示需要解锁之类的图片 类似 1Password 这个app的效果

**Comment by kayanouriko** [comment]
你这几个功能基本实现了
上下滚动就是卷轴滚动，左右滚动就是翻页滚动，取消掉左右点击功能
至于跳页的话就没做了，进度条拖动能快速跳转页码，搭配上书签功能应该足够使用了
最后那个我改成了退回后台的时候显示应用启动页的效果，这需求真有必要么，感觉能拿到你手机的人应该和你也比较亲近了

**Comment by codexss** [comment]
可以改成模糊效果，类似yandex钱包

发自我的 iPhone

**Comment by xioxin** [comment]
解锁图比较好 模糊效果还是能隐约看到一些内容
