### ISSUE TITLE
tableView 在 iOS 11 与 iOS 10中的表现不相同

### ISSUE THREAD

**Issue by umiiii** [kayanouriko/E-HentaiViewer#27]
猜测是约束问题，但是我没用过约束，所以不太好改。
<img width="869" alt="wx20180218-152830 2x" src="https://user-images.githubusercontent.com/29030474/36349378-73f2b656-14c0-11e8-8f0a-49e909946c58.png">
所有 tableView 均有这个问题

**Comment by umiiii** [comment]
self.automaticallyAdjustsScrollViewInsets=NO;
解决方法：在每个Controller中setContent加入此条~
因为我改了项目的一些文件来编译到我自己的机器上，所以我就不commit辣

**Comment by kayanouriko** [comment]
你好,新年快乐..
automaticallyAdjustsScrollViewInsets属性已经在iOS11废弃掉了
所以我的应用不再以automaticallyAdjustsScrollViewInsets属性作为基类属性强行设置为NO,改为用tableview的偏移量调整适应tabbar控制器的布局

通过我的测试,貌似xcode9.2中iOS10的automaticallyAdjustsScrollViewInsets属性已经不生效所以造成错位,修改首页tabbar下面控制器tableview的内容偏移量即可
```
if (@available(iOS 10.0, *)) {

}
else {
    _tableView.contentInset = UIEdgeInsetsMake(UINavigationBarHeight(), 0, UITabBarHeight(), 0);
}
```

**Comment by umiiii** [comment]
明白明白，新年快乐，辛苦你了…我很久没有写过 iOS 了，记忆还停留在 iOS 10，所以不太清楚怎么适配最新版本。
