### ISSUE TITLE
该画廊需要额外处理，暂时不支持预览

### ISSUE THREAD

**Issue by ghost1-source** [kayanouriko/E-HentaiViewer#3]
请问这个是什么情况。。。已经登录了

**Comment by kayanouriko** [comment]
稍安勿躁，网站html更新了与我的解析冲突了，明天我应该会更新一个版本的
感恩

**Comment by ghost1-source** [comment]
（^-^）感谢

**Comment by kayanouriko** [comment]
更新了哦,明天可能还会更新一个新的首页,不过是无关紧要的UI问题

**Comment by ghost1-source** [comment]
之前用过安卓版的，到了ios版发现数据不一样.......之前收藏的都没有了

**Comment by kayanouriko** [comment]
安卓的和我的不是同一个人做的撒,我只是借鉴了他的界面而已[他比我做的好多了..
我的收藏是存储在本地的,配置文件也能通过iTunes导出来,打开就是所有的收藏链接了..
并不是读取你账号的信息..
账号操作这一块一直没时间搞,估计解析完毕还需要很久..
感恩

**Comment by ghost1-source** [comment]
之前安卓机给我格式化了，哈哈哈，不过没什么关系啦，想看还是能找到的，不过完善一下还是好的

**Comment by planktonzp** [comment]
好像還是有一些漫畫會回報 该画廊需要额外处理，暂时不支持预览 比如我搜索一個叫Uzigaya的作者的本子的時候就會出現這個。。。如果您有時間的話希望能夠稍微看下 謝謝了

**Comment by kayanouriko** [comment]
@ruizhipeng 你好
看你提供的作者就知道了,这种题材表站禁止的
你暂时先通过登录账号里站访问吧
这种重定向他给我复现只有一次,调试起来比较麻烦

**Comment by planktonzp** [comment]
@kayanouriko 好的 感谢啦

**Comment by kayanouriko** [comment]
@ruizhipeng 刚刚更新了一个版本,尝试解决了一下你的问题,你可以试试
