### ISSUE TITLE
软件安装新姿势

### ISSUE THREAD

**Issue by hejiheji001** [kayanouriko/E-HentaiViewer#30]
#### 机型 + 系统
iphone 6 / iOS10.2.6 未越狱

#### 运行网络环境
wifi + 有VPN

#### 具体描述
尝试从Diawi https://www.diawi.com 进行安装 提示无法下载软件 不知道能否给予支持

https://www.diawi.com/knowledge-base/iOS/Cant-install-an-app-on-a-device-things-to-check

**Comment by codexss** [comment]
你需要给IPA签名，这只是个分发平台吧

**Comment by hejiheji001** [comment]
@codexss 不是很清楚的说

Diawi is a tool for developers to deploy Development and In-house applications directly to the devices.

1. Upload the iOS or Android application.
2. Send the link to your testers, clients, friends or even use it yourself.
3. Open the link in the browser on the device and click on install.

按照他这样的说法 理论上是可以做到直接安装的 但我不是很懂IOS开发

**Comment by xioxin** [comment]
Diawi是开发者用于将 Development 或 In-house applications 直接部署到设备的工具


Development applications 需要 99美元的个人证书 并录入设备uuid到苹果开发平台 最多100设备
In-house applications 需要 299美元的企业证书 不限设备 一般注册不下来
企业签名国内有蒲公英第三方提供签名服务 价格异常昂贵 6000/年

正如codexss所说 Diawi只负责分发 不负责签名

**Comment by codexss** [comment]
淘宝有卖的UUID证书，20左右，然后没有mac设备的可以去appdb.store在线给ipa签名

xioxin <notifications@github.com>于2018年5月23日周三 下午5:00写道：

**Comment by kayanouriko** [comment]
我倒是有开发者账号，以前想过弄个AdHoc的应用打包，这应用也无法上testflight，嫌一个个录入设备太麻烦随作罢
还是推荐自己签名编译的方式吧
