### ISSUE TITLE
新功能讨论

### ISSUE THREAD

**Issue by kayanouriko** [kayanouriko/E-HentaiViewer#31]
![https://ws1.sinaimg.cn/large/006tKfTcgy1fsk3tfl7t2j30ci0m8102.jpg](https://ws1.sinaimg.cn/large/006tKfTcgy1fsk3tfl7t2j30ci0m8102.jpg)

大概包含这些功能，下面toolbar为上一页，自动播放，跳页，下一页功能

最近家里事情和换了新东家，拖了那么久抱歉了，请再等上一段时间吧Orz

**Comment by xioxin** [comment]
有保存单张到相册的功能吗？

**Comment by Blackssugar** [comment]
新版的浏览器有上下滚动浏览的模式吗？

**Comment by kayanouriko** [comment]
@Blackssugar 这个功能没有单独抽出来，现在暂定的逻辑是竖屏是左右滑动浏览，横屏是你说的滚动浏览
还在调整，看后面有必要抽出来不

**Comment by Blackssugar** [comment]
恩, 不过我个人是比较习惯竖屏上下滚动着看

**Comment by xioxin** [comment]
好期待  什么时候能出来呢?

**Comment by kayanouriko** [comment]
@xioxin 还需要等上两三周吧，现在图片下载模块逻辑还有点不稳定，还在调试中( ; ^ ; )

**Comment by kayanouriko** [comment]
![](https://ws3.sinaimg.cn/large/006tNc79gy1ft009dvgs4j30ci0m8wo6.jpg)
![](https://ws4.sinaimg.cn/large/006tNc79gy1ft009diu59j30ci0m8dn5.jpg)
![](https://ws3.sinaimg.cn/large/006tNc79gy1ft009d9ot6j30ci0m87ci.jpg)
最后修改的样式，还差书签功能没有集成
现在的缓存还有点问题，只要有缓存了就秒加载图片，当画廊更新后并不会更新缓存，因为网站每张图片的唯一标识符需要解析才能获取，做到时刻更新的话需要每次进入看图界面需要加载一段时间，不能做到秒加载，现在有一种解决方案是大图只缓存在本次应用运行期间，下次进入应用就重新请求。
但是我打算开放沙盒路径给你们，你们可以通过itunes备份已缓存的画廊，下载功能是不会做的，这样缓存备份算是折中的方法吧，不过这样就和上面的解决方案冲突了。

**Comment by xioxin** [comment]
能推个开发分支吗 想用

**Comment by kayanouriko** [comment]
@xioxin 当时没开分支，我直接推master了

**Comment by codexss** [comment]
可以释出一个ipa吗，想体验下

**Comment by kayanouriko** [comment]
@codexss 还没改好呢，鸽了几个月，多处解析的bug没修复，功能也没写完

**Comment by xioxin** [comment]
环境：iPhone X iOS12 

 看图 显示 图片获取中 一段时间后崩溃
貌似是网络问题吧 之后又好了
![image](https://user-images.githubusercontent.com/5716100/42413261-558d695c-824f-11e8-87a7-e8994ece716a.png)

启动保护 无法关闭
启动保护不支持面部识别

**Comment by kayanouriko** [comment]
面容保护那一块还没修，下载的明天再看看什么问题

**Comment by kayanouriko** [comment]
@xioxin 你这个我这边貌似复现了， 在未登陆账号的状态下请求官方api会出现请求回调为nil的情况，但是用了几个模拟器来测试，又不是每台模拟器都能复现，现在还发现就算登陆成功，里站也会出现解析不出来的情况，推断和e绅士的cookie的参数有关，搞的头大。。。
