### ISSUE TITLE
IOS12闪退

### ISSUE THREAD

**Issue by Ankhate** [kayanouriko/E-HentaiViewer#32]
#### 机型 + 系统
例: iphone 8 plus / iOS12beta2

#### 运行网络环境
例: wifi + 有VPN

#### 具体描述
安装成功了闪退...非常伤心

**Comment by kayanouriko** [comment]
你用哪种方法安装的？xcode编译？还是7天签名？具体是到哪一步闪退？

**Comment by zszsj1231234** [comment]
七天签名启动应用时会闪退

**Comment by xioxin** [comment]
设置 -> 通用 -> 描述文件 -> 信任开发者

**Comment by BlueandwhiteXD** [comment]
@xioxin 信任了也不行。。。

**Comment by BlueandwhiteXD** [comment]
@Ankhate 我使用Impactor安装的app在iOS12上没过可以正常运行的。。。

**Comment by Kennnnnnji** [comment]
iOS12闪退+1

**Comment by xioxin** [comment]
试试 下载Impactor最新版本

**Comment by Kennnnnnji** [comment]
刚从官网下的0.9.44

**Comment by BlueandwhiteXD** [comment]
@xioxin 你成功用iOS12安装了？

**Comment by xioxin** [comment]
我是使用xcode安装的 没有问题 应该是Impactor暂时还不支持ios12

**Comment by BlueandwhiteXD** [comment]
@xioxin 真羡慕有mac的。我还在和vm斗智斗勇

**Comment by kayanouriko** [comment]
这方面我也无能为力了sad

**Comment by BlueandwhiteXD** [comment]
@Ankhate 用Xcode成功了，iOS12beta3。用虚拟机安装MacOS弄的
