### ISSUE TITLE
請問E-HentaiViewer還沒支援IOS12嗎

### ISSUE THREAD

**Issue by xzc2215** [kayanouriko/E-HentaiViewer#34]
#### 机型 + 系统
iphone 6 s / iOS12 BETA3

#### 运行网络环境
 wifi+4G
 wifi
 飛航模式

#### 具体描述
無法開啟(也有修復閃退)

#### 截图
https://youtu.be/ufwVpZUUFO0 影片

辛苦了作者

**Comment by kayanouriko** [comment]
https://github.com/kayanouriko/E-HentaiViewer/issues/32#issuecomment-403190942
