### ISSUE TITLE
V1.3.0功能讨论

### ISSUE THREAD

**Issue by kayanouriko** [kayanouriko/E-HentaiViewer#37]
这个版本主要跟进网站列表的浏览方式，目前App是强制使用列表样式呈现信息的
改动为根据网站设置中默认呈现方式（列表List / 图片流Thumbnails）做不一样的呈现

目前列表样式调整如下
![](https://ws2.sinaimg.cn/large/006tNbRwgy1fun4j1eetlj30yi1pchdv.jpg)
剔除逻辑上浏览列表时不太关注的是否包含种子和页码信息，提供了比较关注的画廊相关tag信息，不知道大家有啥意见或者建议吗？

图片流样式仅保留预览图，标题，分类和评分四项，相关改进会在这issue更新

**Comment by aiyce** [comment]
解析错误，等待升级版本是什么原因？

**Comment by kayanouriko** [comment]
@aiyce 请尝试科学上网，表站被ban了

**Comment by xioxin** [comment]
列表显示tag确实很方便 我看网页中没有这个功能 数据是怎么加载的 会不会很慢
感觉可以设置关注的tag 列表中标签排序优先显示在最前面 并高亮显示

增加搜索历史或者设置常用搜索

**Comment by kayanouriko** [comment]
@xioxin api回调里面返回了，只是以前没显示而已
关注tag这个以前就想加了的，难得你们中文化还带有每个tag的介绍，我想都利用上，但是还没想到好的呈现方式sad
想单独一个关注tag界面，感觉底部栏又塞满了
现在的tag跳转还复用搜索的界面，这块真心没什么好的处理方法，网上搜了好些漫画UI设计，貌似没啥好的UI呈现符合e绅士的

**Comment by aiyce** [comment]
@kayanouriko 和科学上网无关吧
应该是和设置有关，我重新新建了一个profile之后设置成默认就好了
没有细细排查  怀疑和默认开启Multi-Page Viewer有关系

**Comment by kayanouriko** [comment]
@aiyce 开始你也没说哪个页面的报这个提示。。
翻了一下Multi-Page Viewer貌似是画廊内连续浏览的设置。。我账号没开启到这个功能，等以后我开启了再调试调试

**Comment by kayanouriko** [comment]
考虑了一下，图片流Thumbnails类型还是不做呈现了，优势并不比列表呈现的大，全部统一成列表样式好了。。

**Comment by HUSTHKX** [comment]
可以加一个默认搜索中文吗？

**Comment by xioxin** [comment]
设置面板中可以增加一个 标签wiki 里面列出所有标签和介绍 可以在那里面设置关注操作

**Comment by kayanouriko** [comment]
@HUSTHKX 先上网站设置里面排除其他语言吧或者搜索加上手动加上“language:chinese+关键词” 后面重新支持客户端编辑配置文件就轻松多了，我后面会吧搜索设置里面加上语言排除功能的
@xioxin 在设置里面有点不显眼，我再想想怎么弄吧

**Comment by xioxin** [comment]
查看标签说明 感觉不是什么高频的需求 放设置里挺好

**Comment by kayanouriko** [comment]
@xioxin 还要和快速搜索像结合啊，关注了某标签没有快速查看的入口有点麻烦

**Comment by kayanouriko** [comment]
![](https://ws3.sinaimg.cn/large/006tNbRwgy1fuzuu9jh5rj30yi1pcdsq.jpg)
设置页修改

**Comment by kayanouriko** [comment]
![](http://wx2.sinaimg.cn/mw690/0060lm7Tly1fvcezqt43ej30yi31848t.jpg)
搜索项新增参数预览，样式没找到好的，暂时就用系统原生吧

**Comment by frost134** [comment]
Compile failed: 'YYWebImage.h' file not found

**Comment by kayanouriko** [comment]
@frost134 自己cocoapods更新一下吧

**Comment by z1021804594** [comment]
top list 点进去就闪退，就我一个人这样吗？

**Comment by z1021804594** [comment]
而且ex进不去，显示解析错误，等待更新 ehentai正常

**Comment by kayanouriko** [comment]
@z1021804594 toplist确实又闪退了，api貌似又抽风了。。。你如果用了科学工具的话切换一下线路吧，可能是线路问题，尽量避免用亚洲的线路。。。ipa貌似没有修改开关默认状态，请先登陆账号再浏览里站

**Comment by asdchange7** [comment]
大佬 你能支援ios12吗

**Comment by asdchange7** [comment]
或者 上架别的区的苹果商店可以吗 ios没有越狱啊

**Comment by asdchange7** [comment]
omg 各位 imp失败 应该是版本的问题 我 0.95所以不行 升级到 0.97完美 12.0.1在这里 假设上架了appstore 我一定会出力的

**Comment by kayanouriko** [comment]
@pjxcsrt321 不会上架的，喜欢折腾的话试一试虚拟机编译项目安装

**Comment by xzc2215** [comment]
搜尋的地方 希望在框框可以案搜尋的符號 不使用鍵盤上的搜尋更好

**Comment by Nekondesu** [comment]
希望加： 本子信息栏，可以复制本子的英/日标题，… 虽然搜索同类画廊可以得到本子名（但好想直接复制呀
图床：

![](https://i.loli.net/2018/11/07/5be2f85b4e79d.png)

**Comment by kayanouriko** [comment]
@Asakinb 可以，不过最近没什么时间更新应用了sad

**Comment by Nekondesu** [comment]
嗯哼好的呢 另外本子缓存功能可不可以考虑实装呢😄

**Comment by kayanouriko** [comment]
@Asakinb 图片已经实现缓存了，你浏览过的图片都会缓存起来的。
只是没开放导出而已，越狱了的话，可以用各种助手查看到缓存的图片。

**Comment by Nekondesu** [comment]
了解了～ 不过根据使用体验，现有情况好像不需要再给个“缓存”按钮。（不过要是开放导出不就成真·本子下载器了吗…）

**Comment by CynicalHeart** [comment]
对我这种没钱买mac还安不上虚拟机的人真滴绝望。还有我想问下dalao，你知道这个程序被一些人卖么。。。

**Comment by kayanouriko** [comment]
@CynicalHeart 我说最近怎么浏览量不正常呢，还有人看得起我这代码拿去卖啊。。他们真是比我的代码还渣了。。

**Comment by xioxin** [comment]
在哪里 想见识见识

**Comment by CynicalHeart** [comment]
你太谦虚了吧~   我在安picacg的时候看到了你的程序，问了下 20才给ipa，估计也是用cydia安装吧。
ios哔咔漫画 的 苹果哔咔下载 加了QQ后主动问起这个软件就要收钱的，15-30，这个是主动问收钱。淘宝上搜魔芋助手 有很多需要破解的软件 或者根本没有注册的软件，看到大佬你的程序啦，还需要会员~

**Comment by kayanouriko** [comment]
唉，你们啊，现在类似的站点比前两年多了不少了，专门对手机版做了优化的也不在少数。。
多动手找一下未免没有，非要用最麻烦的模式，说到底还是有钱人太多了。。

**Comment by FolStone** [comment]
折腾一天mac虚拟机装好了（微笑），另外希望能考虑下ipad上的显示效果，相比DaidoujiChen的版本，大佬的app在ipad上的显示效果更好一些，全面屏本子什么的……当然列表也比那边更好看一点，反而担心新版列表的效果。
现在在ipad上的列表显示的话已经有点显得标题下空白很大了，另外就是左右在上下滚动时，会在封面可以顶满的情况下留下黑边
都是小问题，我是觉得现在版本就挺好用的了……

**Comment by kayanouriko** [comment]
@qq938403611 我应用还没开始做ipad版呢，只是以前有人说需要ipad版我才把应用改为通用配置的，只是强制拉伸一下iPhone版的UI而已，收藏页面的按钮在ipad下面还会崩溃呢。
iphone版要做的功能都还没修好呢现在。。。唉，下半年没什么好事情，都没时间做这项目了。。

> 现在在ipad上的列表显示的话已经有点显得标题下空白很大了，另外就是左右在上下滚动时，会在封面可以顶满的情况下留下黑边

左右滚动和上下滚动应该是冲突的选项才对。。。没看懂是什么意思

**Comment by FolStone** [comment]
> 左右滚动和上下滚动应该是冲突的选项才对。。。没看懂是什么意思

……指的是左右两侧，会在向下滚动的时候匹配最宽的图片而留下黑边，不过好像是扫图时候为了对齐故意留下的？

但是几天体验，两边都没有对读取失败图片的刷新功能，不得不多次退出浏览重进……这点才是强烈建议添加的功能

另外也非常感谢dalao的付出~

**Comment by kayanouriko** [comment]
@FolStone 那应该是图片本身就是这样的，上下滚动的模式下，只有图片底部会有黑边间距，是为了分辨出两张图片的边距，左右是紧贴屏幕匹配图片宽度的。
关于失败图片那个本来是请求失败后会有个按钮，点击之后重新请求的，逻辑没做完。现在是自动重新刷新的，不用退出重进，打比方说，第一页请求失败了，你先滚动到第三页，再返回第一页，第一页就会重新请求图片了。

**Comment by FolStone** [comment]
> @FolStone 那应该是图片本身就是这样的，上下滚动的模式下，只有图片底部会有黑边间距，是为了分辨出两张图片的边距，左右是紧贴屏幕匹配图片宽度的。
> 关于失败图片那个本来是请求失败后会有个按钮，点击之后重新请求的，逻辑没做完。现在是自动重新刷新的，不用退出重进，打比方说，第一页请求失败了，你先滚动到第三页，再返回第一页，第一页就会重新请求图片了。

原来如此，非常感谢~

**Comment by chinajack1993** [comment]
eh可以正常上ex上不了，换美国ip也不行
，daihentai倒是能上里站但是很不好用
![img_1497](https://user-images.githubusercontent.com/46300701/50575020-28aa1e00-0e2f-11e9-9292-0a24a2f2a113.PNG)
![img_1496](https://user-images.githubusercontent.com/46300701/50575021-2942b480-0e2f-11e9-853a-25c2712f8e7b.PNG)
![img_1495](https://user-images.githubusercontent.com/46300701/50575022-2942b480-0e2f-11e9-98b8-eef09589ff5b.PNG)

**Comment by Nekondesu** [comment]
@chinajack1993 设置里面站点切换了吗 挂着梯子应该没问题…

**Comment by chinajack1993** [comment]
![img_1499](https://user-images.githubusercontent.com/46300701/50575665-631ab780-0e3d-11e9-83eb-b38567060378.PNG)
![img_1498](https://user-images.githubusercontent.com/46300701/50575666-644be480-0e3d-11e9-9dad-493316c6c0de.PNG)
都试了没用 @Asakinb

**Comment by YLaido** [comment]
感谢作者辛勤更新。
但是最新一版“收藏”和“搜索”结果里的作品全部报“载入出错”。只有“当前热门”里才能正常看到。梯子是没有问题的，首次登陆也用的美国。虚拟机用的VMware15，MacOS 10.14
机型：iphone se 
系统：10.3.2
以下是log:
[log.txt](https://github.com/kayanouriko/E-HentaiViewer/files/2741360/log.txt)

**Comment by allen9630308** [comment]
感謝作者的努力
希望可以如同舊版增加tag收藏的功能

**Comment by applemiku** [comment]
那个新11寸ipadpro可以适配一下吗？

**Comment by kayanouriko** [comment]
@applemiku 新pro应该是已经适配好的了，部分布局可能没适配完美而已
以后ipad会重构一个全新布局版本的，目前该项目暂时搁置了

**Comment by nukewarrior** [comment]
可否给热门、画廊、搜索等地方加上过滤器呢，比如说，我就只想看到英文活中文的内容

**Comment by Nekondesu** [comment]
@nukewarrior  搜索时添加语言标签就行，直接空格加 Chinese。热门和画廊怕是不行，网站语言筛选我这边没用，您可以试试

**Comment by kayanouriko** [comment]
@nukewarrior 热门是不支持筛选的
然后你说的这些网站已经支持了，需要你登陆账号
画廊列表你需要用浏览器打开你的账号，设置里面其他选项默认，把语言筛选设置成你想要的，生效设置，再重新打开app就生效了
搜索是有筛选设置的，你再找找

**Comment by nmfws** [comment]
你好，这几天EH相关app好像都炸了……安卓端的ehviewer昨天更新1.50后才修复，希望大佬也能修复一下，感谢！

**Comment by h55073365** [comment]
这个版本在哪里可以下载…

**Comment by kayanouriko** [comment]
实在抱歉，最近换了新东家，刚好遇上提版期，别催了，再耐心等待一下，新版本在做了
![https://ws3.sinaimg.cn/large/006tKfTcgy1g1kykm9nqyj30nu1fktj0.jpg](https://ws3.sinaimg.cn/large/006tKfTcgy1g1kykm9nqyj30nu1fktj0.jpg)

**Comment by chinajack1993** [comment]
版主是干啥的呀？会u3d不？可以来我公司，公司现在少个喜欢二次元的u3d
