### ISSUE TITLE
进入阅读页面闪退

### ISSUE THREAD

**Issue by Nekondesu** [kayanouriko/E-HentaiViewer#38]
#### 机型 + 系统
例: iphone 7 plus / iOS10.2.6
Iphone8 ios11.2.5 未越狱
#### 运行网络环境
例: wifi + 有VPN
宁波电信 wifi 使用自搭建的ssr，洛杉矶VPS
#### 具体描述
例: 无法获取画廊列表
使用此版本与上一版本，进入任意阅读版面，点击阅读，加载中就会闪退，另外D-hentai那边有个类似描述：“這是因為最近 EH 那邊把config放到上了server 而不是以往的cookie”。我觉得这可能与该问题无关
#### 截图
例: ![](图片地址)
闪退啊，提取信息什么的咱家实在是不会

**Comment by Nekondesu** [comment]
反馈：刚刚，同样的网络环境，突然可以使用画廊、收藏、搜索栏功能了，也可以进入阅读页面了，没有发生闪退。》》》》》》》》》》赞美大大的辛劳付出~

**Comment by kayanouriko** [comment]
使用过上个版本覆盖安装的，由于缓存数据库我没做升级判断，所以会闪退，卸载重装就好了。。
