### ISSUE TITLE
请教“解析错误，等待升级版本"

### ISSUE THREAD

**Issue by Nekondesu** [kayanouriko/E-HentaiViewer#39]
#### 机型 + 系统
例: iphone 7 plus / iOS10.2.6
iPhone8 ios11.2.5 未越狱
#### 运行网络环境
例: wifi + 有VPN
宁波电信 WiFi 自搭建SSR 洛杉矶VPS
#### 具体描述
例: 无法获取画廊列表
使用代理且可以正常浏览表站，但在APP内画廊、收藏、搜索栏 均提示解析错误，
且我登陆的ID是新注册的，暂时无法进入里站，是否与此有关？
#### 截图
例: ![](图片地址)

**Comment by Nekondesu** [comment]
反馈：刚刚，同样的网络环境，突然可以使用画廊、收藏、搜索栏功能了。原因不明

**Comment by Nekondesu** [comment]
反馈：原因已经找到 如果e站账号没有进入里站权限，或不登陆账号，选择了里站站点，就会出现解析失败和闪退的bug

**Comment by kayanouriko** [comment]
这由于我一开始吧默认站点选成里站的缘故，开关那里我做有登陆账号的判断的，我下个版本改一下
收藏界面第一次加载肯定是没数据的，用网页版也是这样，再次刷新就好了
