### ISSUE TITLE
收藏能进去但是什么都看不到也什么都点不到。。。

### ISSUE THREAD

**Issue by ghost1-source** [kayanouriko/E-HentaiViewer#4]
OK，又是我，感觉应该不是我个人的问题。。

**Comment by kayanouriko** [comment]
你说的收藏是指tag收藏还是你的账号画廊收藏？
如果是画廊收藏，登陆账号后需要在收藏页面下拉手动刷新一次才能获取收藏内容~没有账号是无法使用收藏功能的
如果是tag收藏，则需要在tag页面收藏过tag才会显示，这个是本地的，有无账号都能使用
修仙=，，= zzZZ

**Comment by ghost1-source** [comment]
账号的收藏，画廊的收藏倒是能正常使用，账号收藏忘记有没有刷新过了。。。手机没越狱，现在用不了，打开就闪退，要重新装过，好烦，同修仙中=，，= zzZZ

**Comment by ghost1-source** [comment]
哦，对了，上百页的漫画中，似乎只能加载到40，80，120页，原因未知

**Comment by kayanouriko** [comment]
@HeavenRoyalStar 我自己用着没问题的说，最近也有人提到闪退，他后面就没回复过我了，你们是用那个软件签名安装的么。。。那个貌似有7天期限。。。
我的网络请求逻辑没有重载方法，所以网络不稳定所以解析中断了，页数多的页码容易出现这问题。。
这应用还存在不少的小问题。。

没时间改啊，年后就好忙了。。自己好懒啊。。
你还是多关注一下DaidoujiChen的3.0吧。。Orz

**Comment by ghost1-source** [comment]
越狱不了没啥办法。。。只能用那个安装，没有时间就放着先吧，应该大部分用户没啥问题的，daidoujichen的dai-hentai之前用过，好像很久没更新了，Orz，另外，下载功能。。。咳，没事，好了，早点睡吧hhh
