### ISSUE TITLE
图片获取失败

### ISSUE THREAD

**Issue by kenmingwang** [kayanouriko/E-HentaiViewer#40]
#### 机型 + 系统
Ipad mini 4 / ios 9.3 越狱环境

#### 运行网络环境
wifi + 墙外网络

#### 具体描述
阅读的时候图片加载失败，预览，画廊其他一切ok

#### 截图
![_20181010210356](https://user-images.githubusercontent.com/35542088/46778233-0beac800-ccd0-11e8-8805-5c75e7ed21f4.jpg)

**Comment by kayanouriko** [comment]
试一下Safari可以浏览图片吗？
切换一下你的科学上网站点试试，出现这个提示有两个，一个是网络中断了，一个是网站的api失效了，但是我这边是好好的。。

**Comment by kenmingwang** [comment]
> 试一下Safari可以浏览图片吗？
> 切换一下你的科学上网站点试试，出现这个提示有两个，一个是网络中断了，一个是网站的api失效了，但是我这边是好好的。。

Emm 是可以的，我是在国外所以没墙，主要是预览什么的都ok，就是点进去看不了- -

**Comment by kayanouriko** [comment]
只能摊手了，前面也有一个在欧洲的issue，也是换了一个科学上网约好了…
