### ISSUE TITLE
可以正常阅读，但是预览图不显示

### ISSUE THREAD

**Issue by cafrew** [kayanouriko/E-HentaiViewer#41]
#### 机型 + 系统
iphone 8 plus / iOS11.3.1

#### 运行网络环境
wifi + 有VPN

#### 具体描述
可以正常阅读，但是预览图不显示。
APP版本号：1.2.0(4)

#### 截图
https://m.imgur.com/a/ojuCHc2

**Comment by kayanouriko** [comment]
请登录账号，无账号无法解析预览图。。。数据结构不一样，当时我手贱把逻辑删除了。。后面一直懒得重写
