### ISSUE TITLE
在app里上不了ex

### ISSUE THREAD

**Issue by goouttoplayno** [kayanouriko/E-HentaiViewer#42]
#### 机型 + 系统
iphone 8 plus / iOS11.2.1

#### 运行网络环境
wifi + 有VPN

#### 具体描述
有可以进ex的账号，在电脑，手机的浏览器上都可以裸连ex，但是在app里只能挂vpn上表站，换成ex就说解析错误，等待升级版本。

#### 截图
https://pan.baidu.com/s/1qF04uDZKIz2NGQvP5kgXKw

**Comment by goouttoplayno** [comment]
其实之前还有个问题，就是同一个账号电脑上浏览器可以上ex，手机浏览器上不了，每次都是熊猫，然后我下了个uc把浏览器标识换成电脑以后就可以上了。之后又在uc里把浏览器标识换成ip，又刷新一次已经打开的ex网页发现也能上，没有熊猫了，之后再去之前不能用的浏览器里发现也能上ex了

**Comment by kayanouriko** [comment]
尝试一下退出登录之后在登录页面有个删除cookie的选项，点击一下再重新登录
或者更换一个新线路
网络问题太复杂了，我实在重现不了。。
后续我集成个日志回收功能再观察一下这个功能。。。

**Comment by aiyce** [comment]
我以前也有这个问题，后来重置设置就好了
怀疑是由于设置显示缩略图而不是列表

**Comment by kayanouriko** [comment]
@aiyce 应该不是设置缩略图显示的原因，因为我项目里面是强制采用列表形式解析的，这个和你网站的设置没有关系，不过你这个回复证明了有可能是设置里面某些选项影响了解析，楼主可以暂时按照楼上这个童鞋的做法先试一下吧

**Comment by goouttoplayno** [comment]
@aiyce 你说的重置设置是哪里重置？ 在ex和e的设置里我也试着改了那个缩略图和列表的选项了 也还是没用T_T

**Comment by aiyce** [comment]
settings-create new

**Comment by goouttoplayno** [comment]
@aiyce 看来我是凉了 怎么折腾都没用

**Comment by damien00** [comment]
> @aiyce看来我是凉了怎么折腾都没用

尝试用美国梯子重新登录客户端试试 日本的是不行的

**Comment by goouttoplayno** [comment]
@damien00  试了 换了之后画廊显示网络错误 不知道是不是vpn的锅 当前热门倒是能刷出来列表 但是点进去看不了

**Comment by damien00** [comment]
> @ daminen00试了换了之后画廊显示网络错误不知道是不是vpn的锅当前热门倒是能刷出来列表但是点进去看不了

我之前的情况和你是一模一样的，后来想起来客户端第一次登陆EX需要美国VPN就好了，我是IOS12没越狱 用的叉叉IPA精灵自己传的ipa

**Comment by goouttoplayno** [comment]
@damien00 厉害厉害 终于弄好了
