### ISSUE TITLE
闪退+解析错误

### ISSUE THREAD

**Issue by Krazymud** [kayanouriko/E-HentaiViewer#43]
#### 机型 + 系统
例: iphone 7 / iOS12.0.1

#### 运行网络环境
例: wifi + 有VPN

#### 具体描述
例: 获取图片闪退，画廊显示解析错误

#### 截图
例: 
![0](https://user-images.githubusercontent.com/22273043/47963748-2b74d680-e06b-11e8-9345-75e70ec35356.jpg)
)

**Comment by kayanouriko** [comment]
参照 https://github.com/kayanouriko/E-HentaiViewer/issues/42#issuecomment-435727826

**Comment by damien00** [comment]
你挂了哪里的梯子？客户端第一次登录进EX需要挂美国的梯子哦 这个和自带浏览器没关系，我浏览器能进EX客户端照样闪退，只能美国 其他地区都不可以 我之前也是进EX就闪退吧这个查给忘了，今天重新试了下一切正常

**Comment by SpaceEggs** [comment]
我也遇到这个问题。
按照楼上说的换美国梯子，清除cookie重新登陆后就可以了。

**Comment by 13025309325** [comment]
各位能发个编译好的没越狱版的 包嘛?
