### ISSUE TITLE
繁體中文化

### ISSUE THREAD

**Issue by OtakuXavier** [kayanouriko/E-HentaiViewer#44]
我只是單純一個coding萌新
然後想對整個介面進行繁體中文化
但找不到localizable.string在哪裡
請問有人知道嗎？
還是這個app的介面語言string檔不叫localizable?

**Comment by kayanouriko** [comment]
抱歉，現在才看到，這項目一開始就沒有考慮做多語言支持的處理，文本全部分散寫死在代碼和xib裏面的。
