### ISSUE TITLE
编译 无法找到  YYWebImage.h

### ISSUE THREAD

**Issue by JamasChuang94** [kayanouriko/E-HentaiViewer#45]
#### 机型 + 系统
 iphone 8 / iOS12.1.3

#### 运行网络环境
wifi + 有VPN

#### 具体描述
编译 无法找到  YYWebImage.h

求助

**Comment by kayanouriko** [comment]
自己重新拉取一下cocoapods吧

**Comment by 13025309325** [comment]
> 自己重新拉取一下的CocoaPods吧

大佬，我不是很懂ios 下的开发。。。，是https://github.com/kattrali/cocoapods-xcode-plugin 这个库吗？

**Comment by JamasChuang94** [comment]
> 自己重新拉取一下的CocoaPods吧
貌似 收藏无法使用。。 还有热门ex 使用会闪退普通没事

**Comment by kayanouriko** [comment]
第一次收藏是获取不到的，下拉刷新一下就好了
热门api日常抽风，过段时间再试试
你在网页端启用默认配置再打开app里站试试，目前的解析不能完全兼容任意配置，还有爬issue查看别的解决方案，有可能是科学姿势的问题

**Comment by JamasChuang94** [comment]
> 第一次收藏是获取不到的，刷新下拉就好一下了
> 热门API日常抽风，段过时间再试试
> 你在|网页端的启用默认配置再打开的应用程序里站试试，目前的解析不能完全兼容任意配置，还有爬问题查看别的解决方案，有可能是科学姿势的问题

我用的就是默认配置。。。而且我安卓的客户端也没问题。。。

**Comment by kayanouriko** [comment]
可能是科学姿势的问题了，爬issue看看别的解决方案吧，还不行只能摊手了
