### ISSUE TITLE
如何整本下载

### ISSUE THREAD

**Issue by PeroPer0** [kayanouriko/E-HentaiViewer#46]
#### 机型 + 系统
例: iphone 8 / iOS10.12.2

#### 运行网络环境
例: wifi + 有VPN

#### 具体描述
例: 你好,如何整个下载?只能点进图片一张张的保存

#### 截图
例: ![](图片地址)

**Comment by kayanouriko** [comment]
你好，并没有提供下载功能。
你可以通过应用获取画廊提供的磁力链接另外进行下载
