### ISSUE TITLE
反馈2个问题(加载不全和收藏夹崩溃)

### ISSUE THREAD

**Issue by hnboy2005** [kayanouriko/E-HentaiViewer#5]
感谢做了这个App,赞!
有两个问题反馈一下:
1 图片加载的时候,是不是以40张为单位? 有的本子有100页,但是加载时偶尔有只能加载40页或是80页的情况.(在多个本子中偶尔随机出现)
2 点击进入收藏夹就崩溃退出了, 一开始是以为某个本子有问题,一个一个在网站上取消收藏,再尝试刷新app的收藏夹,发现收藏夹全部清空了, app打开收藏夹还是崩掉(前几个版本好像没这个问题)

**Comment by kayanouriko** [comment]
你好!
1. 属于已知问题,具体原因参照:https://github.com/kayanouriko/E-HentaiViewer/issues/4 5楼
这个问题会在下个版本连同新的图片浏览器一起更新发布,不过应该要半个月到一个月左右,有点忙...

2. 你这描述有点看不懂,先"尝试刷新app的收藏夹,发现收藏夹全部清空了",然后"app打开收藏夹还是崩掉",那到底收藏夹崩溃没崩溃=,=,我拿自己的账号测试收藏夹功能使用正常的说,参照:https://github.com/kayanouriko/E-HentaiViewer/issues/4 2楼

感恩

**Comment by hnboy2005** [comment]
不好意思,描述有些不清晰,是这样的
我网站的收藏夹里大概有30个本子, 目前在App里一点击收藏夹,App就自动退出了.
我怀疑是不是某个本子标题有非法字符, 所以做了一个测试, 在网站上把收藏的本子一个一个取消收藏,
每次取消一个本子,就在App上刷新下收藏夹,看看是不是正常了
结果发现, 就算把所有的收藏夹里的本子都取消收藏了, App点击收藏夹,还是崩溃,所以应该不是我推测的那个问题.
(但是我记得收藏夹上个月好像是正常的,所以不知道是新版的问题,还是其他问题了)
供参考.

**Comment by kayanouriko** [comment]
@hnboy2005 你好!
我自己的账号测试了一下释出包和编译包都没出现闪退现象Orz
上个版本的收藏夹是本地存储的,并没有和网站的关联,所以没事...
新版本是直接读取网站你账号的收藏夹页面的收藏信息..
你再按流程走一遍试试吧,卸载应用重装,先登录账号,再去收藏夹看看=,=如果还是不行我也没辙啦..

**Comment by hnboy2005** [comment]
好的,谢谢!
