### ISSUE TITLE
iPad收藏栏进行编辑时闪退

### ISSUE THREAD

**Issue by aszmax0007** [kayanouriko/E-HentaiViewer#50]
#### 机型 + 系统
iPad Air 2 / iOS12.1.4
iPhone 8  / iOS12.1.4

#### 运行网络环境
wifi/移动网络 海外无VPN

#### 具体描述
iPad上点击收藏栏**左上角**的按钮（移至别处/取消收藏）时闪退，而iPhone上可以正常操作

#### 截图
无

**Comment by kayanouriko** [comment]
以前的低级代码错误，一直没在ipad使用这个功能所以没测出来
到时候连同昨天的列表解析问题一起更新一个新版本~
另外iPad是计划出单独优化版本的~

**Comment by aszmax0007** [comment]
> 以前的低级代码错误，一直没在ipad使用这个功能所以没测出来
> 到时候连同昨天的列表解析问题一起更新一个新版本~
> 另外iPad是计划出单独优化版本的~

幸苦了！期待ing！

**Comment by kayanouriko** [comment]
新版本已修正
