### ISSUE TITLE
提示解析错误

### ISSUE THREAD

**Issue by zszsj1231234** [kayanouriko/E-HentaiViewer#51]
iPhone 6s ios12.1.1 已越狱
今天貌似ehentai网页改版了现在app没办法读取了。

**Comment by kayanouriko** [comment]
稍微等等吧，到时候我顺带把新功能一并加上更新一个版本

**Comment by sdshdv** [comment]
https://forums.e-hentai.org/index.php?showtopic=225016  这个是E站改版信息的汇总

**Comment by nmfws** [comment]
> 稍微等等吧，到时候我顺带把新功能一并加上更新一个版本

麻烦大佬了

**Comment by zszsj1231234** [comment]
> https://forums.e-hentai.org/index.php?showtopic=225016 这个是E站改版信息的汇总

麻烦大佬了

**Comment by h55073365** [comment]
我想问一下这个版本怎么升级目前1.2 而且目前显示解析错误

**Comment by h55073365** [comment]
大佬…跪求解决 解析错误等待版本更新 😢

**Comment by junweifeng** [comment]
新版本请增加11寸ipad分辨率支持，感谢

**Comment by h55073365** [comment]
大佬，啥时候更新哟

**Comment by Andy59** [comment]
等不及的可以自己搜索@"//div [@class='it5']//a" 替换为 @"//td [@class='gl3c glname']//a"   
@"//div [@class='id3']//a" 替换为 @"//td [@class='gl2c']//a" 

            [idArray addObject:@[splitStrings[splitCount - 3], splitStrings[splitCount - 2]]];
            if (nil == baseUrl) {
                baseUrl = eachURLString;
            }   这一段替换为
        if (splitCount == 7) {
            [idArray addObject:@[splitStrings[splitCount - 3], splitStrings[splitCount - 2]]];
            if (nil == baseUrl) {
                baseUrl = eachURLString;
            }
        }
        else if ([eachURLString containsString:@"?"]) {
            NSRange range = [eachURLString rangeOfString:@"?"];
            NSString *propertys = [eachURLString substringFromIndex:(int)(range.location+1)];
            NSArray *subArray = [propertys componentsSeparatedByString:@"&"];
            NSMutableDictionary *tempDic = [NSMutableDictionary dictionaryWithCapacity:4];
            for (int j = 0 ; j < subArray.count; j++) {
                NSArray *dicArray = [subArray[j] componentsSeparatedByString:@"="];
                [tempDic setObject:dicArray[1] forKey:dicArray[0]];
            }
            [idArray addObject:@[tempDic[@"gid"], tempDic[@"t"]]];
            if (nil == baseUrl) {
                baseUrl = eachURLString;
            }
        }
然后重新跑一次

**Comment by kiritoxkiriko** [comment]
> @"//td [@Class='gl2c']//a"

老哥...改了之后重新编译还是解析错误啊

**Comment by CosimoZi** [comment]
翘首以待

**Comment by Lemon2ee** [comment]
大佬加油

**Comment by ryankwan425** [comment]
還要多久啊想打丁丁了

**Comment by kiritoxkiriko** [comment]
可以先用隔壁的dai-hentai

**Comment by kayanouriko** [comment]
新版本已release

**Comment by tianliangz** [comment]
> 新版本已release

登陆ex还是会出现解析错误啊大佬

**Comment by kayanouriko** [comment]
@tianliangz 请网页创建一版默认配置文件试试看

**Comment by DDG25** [comment]
10.3.3的是不是悲剧了？

**Comment by kayanouriko** [comment]
@DDG25 非常抱歉，最低系统要求提升到iOS11了

**Comment by tianliangz** [comment]
不太懂，请问“网页创建一版默认配置文件”具体怎么做😂

**Comment by kayanouriko** [comment]
@tianliangz 用手机浏览器看能不能登陆里站，能的话去里站设置里面创建一份默认配置文件，然后再回到app刷新试试
