### ISSUE TITLE
应用最低iOS版本没法降低了么？

### ISSUE THREAD

**Issue by Golubb** [kayanouriko/E-HentaiViewer#52]
升级1.3.1了可喜可贺，但是最低iOS版本没法降低了么？我还在iOS9呃...

**Comment by xioxin** [comment]
升级系统吧

**Comment by kayanouriko** [comment]
抱歉了，项目主要界面采用了11.0的控件，所以这个没办法了
你可以尝试一下隔壁的应用，他的最低版本还是8，该项目是从他那里发展而来的。 
https://github.com/DaidoujiChen/Dai-Hentai

**Comment by Golubb** [comment]
> 升级系统吧

现在升级就只能升12.2，没法越狱了。而且我这老设备也拖不动了吧...

**Comment by Golubb** [comment]
> 抱歉了，项目主要界面采用了11.0的控件，所以这个没办法了
> 你可以尝试一下隔壁的应用，他的最低版本还是8，该项目是从他那里发展而来的。
> https://github.com/DaidoujiChen/Dai-Hentai

谢谢，我试下
