### ISSUE TITLE
iPhone X 图标模糊

### ISSUE THREAD

**Issue by xioxin** [kayanouriko/E-HentaiViewer#53]
#### 机型 + 系统
iPhone X / iOS 12.3

#### 具体描述
图片素材模糊

#### 截图
![IMG_7232](https://user-images.githubusercontent.com/5716100/56638433-c6588000-66a0-11e9-9d63-7ffc0a87cc7f.jpg)

希望增加关注列表（就是最近网页版新增的功能）
和关注tag自定义颜色

**Comment by kayanouriko** [comment]
图标网上拿的，分辨率低了。。
关注列表其实想加进来的，发现工作量有点大，就放到下一版了。。
你不来个flutter版e绅士么？感觉这个项目代码已经被我玩坏了，我想敲碗等你的呢_(°:з」∠)_

**Comment by xioxin** [comment]
我还真有计划制作flutter版本 不过工作太忙 一直搁置到现在 几乎啥也没写

**Comment by kayanouriko** [comment]
我还有个mac版本半成品丢在私人仓库坑着呢Orz
也有计划弄个可定制站点规则解析的应用，扩展到e绅士以外的站点，不过看现在市场上已经有了一个了，自己也没什么动力做了

**Comment by xioxin** [comment]
我的思路也是可配置的 原本打算上架赚点外快 通过js代码写解析 类似jsbox 跨平台

发自我的 iPhone

**Comment by kayanouriko** [comment]
现在市场上已经有的那个真的是按功能点解锁收费。。

**Comment by kayanouriko** [comment]
换了高清图片，这issue我先关了

**Comment by xioxin** [comment]
> 你不来个flutter版e绅士么？感觉这个项目代码已经被我玩坏了，我想敲碗等你的呢_(°:з」∠)_

我开始用flutter来写漫画软件了, 不过现在计划是先做一个本地图书. 和访问局域网共享. 类似ComicGlass.

flutter 库还是太少了, 尤其是那些比较基础老旧的技术.

**Comment by kayanouriko** [comment]
@xioxin 加油，我的swift版还在私仓里改来改去呢Orz

**Comment by xioxin** [comment]
需要实现smb访问, 没有现成的库, 在照着200多页的技术文档写 😂 
刚吧基本的写完 登陆, 读取目录,读取文件.

跟字节打交道真是累

按需解压前几个周也实现了, 今晚整合测试 应该可以直接读取NAS里的zip漫画了. 不用下载, 想想就兴奋.
