### ISSUE TITLE
關於一些別的bug

### ISSUE THREAD

**Issue by asdchange7** [kayanouriko/E-HentaiViewer#54]
eh高級設置似乎很久了 高級搜索點開始有機率閃退 
點tag後想加個中文搜索發現似乎不行

**Comment by asdchange7** [comment]
如果還能有tag收藏和搜索歷史紀錄就更好了 
謝謝大大的付出

**Comment by kayanouriko** [comment]
感谢反馈
>  eh高級設置似乎很久了
1. 高级设置改成云端配置了，我太垃圾了，解析配置同步配置好累，一直没动手改【拖延症
> 高級搜索點開始有機率閃退
2. 闪退具体是指哪一步操作呢？点击搜索按钮开始搜索的时候？
> 點tag後想加個中文搜索發現似乎不行
3. 我测试是没问题，本质还是wiki中的提到的高级搜索方法：类别限制+关键词，是支持中文的。
    主要是现在高级筛选的tag提示是全部类型的，你可以在artist分类下搜到famele的tag，这样的话会搜索不出来结果的。
   ![](https://ws4.sinaimg.cn/large/006tNc79gy1g2du5lzrsvj30u01sx7gc.jpg)
> 如果還能有tag收藏和搜索歷史紀錄就更好了
4. tag收藏下版会加入的
5. 现在这搜索功能做历史搜索可能有点复杂，我再想想更好的解决方案

**Comment by asdchange7** [comment]
现在发现高级设置闪退似乎不常见 不过我在搜索里不搜东西单纯筛选manga会没有东西 下拉 会闪退

**Comment by asdchange7** [comment]
诶 在漫画里点开tag 只是引号加tag啊

**Comment by kayanouriko** [comment]
> 不过我在搜索里不搜东西单纯筛选manga会没有东西 下拉 会闪退

这个可以，原来计划这样是不让刷新的，现在看来也有单看某个类别的需求，我再改改吧
> 在漫画里点开tag 只是引号加tag啊

嗯，因为换了搜索控件，现在搜索只做在外面了，标签就直接是数据呈现不允许二次修改搜索了，这个其实改了好久，我也知道不怎么方便，但是有些问题没能解决，就暂时先这样了

**Comment by kayanouriko** [comment]
> 高級搜索點開始有機率閃退

这个我找到问题所在了

> 不过我在搜索里不搜东西单纯筛选manga会没有东西 下拉 会闪退

这个也修复了，现在也支持不带任意关键词和高级筛选搜索了

这个issue我先关闭了哈
