### ISSUE TITLE
v1.4.0版本功能讨论

### ISSUE THREAD

**Issue by kayanouriko** [kayanouriko/E-HentaiViewer#55]
主要是新增mytags功能，实现完全版的原生控件操作，还意外发现了官方api有标签查询功能，配合EhTagTranslator能实现大部分的转化操作了，就是这个api只能识别罗马音有点可惜，并且部分操作居然实现了api post方式操作。
外加补加一个watched的tab页的话，有了这个mytags功能，基本标签这一块能满足大部分的定制需求了
另外还修正了一些老问题，把评论评分等一些缺失的功能在补补就能再发个版本了。
今后可能想专注优化一下一直被搁置看图模块，现在的看图下载逻辑还是有点慢，但是请求快了又怕被识别为爬虫，这个有点蛋疼。
还有什么想要优化或者修改的地方也可以提出来，我看简单的也都在这一版上了~
如图
![](https://ws1.sinaimg.cn/large/006tNc79gy1g2l49nxq59j30u01sx7wh.jpg)
![](https://ws3.sinaimg.cn/large/006tNc79gy1g2l49nnn9qj30u01sxzvz.jpg)
![](https://ws2.sinaimg.cn/large/006tNc79gy1g2l49ngqpdj30u01sx7aa.jpg)
![](https://ws4.sinaimg.cn/large/006tNc79gy1g2l49n8tbkj30u01sx13q.jpg)
![](https://ws4.sinaimg.cn/large/006tNc79gy1g2l49n0y3xj30u01sxh8d.jpg)

**Comment by BlueNeet** [comment]
加一个搜索的结果也能翻页的功能吧

**Comment by kayanouriko** [comment]
@BuleNeet 这个在搜索里面貌似加有点麻烦。。我再想想怎么改好吧

**Comment by BlueNeet** [comment]
> @BuleNeet 这个在搜索里面貌似加有点麻烦。。我再想想怎么改好吧

麻烦你了，加油

**Comment by sakurrasama** [comment]
可以先把这个版本放上来吗 ･∀･)ﾉﾞ

**Comment by xioxin** [comment]
真是🐂🍺坏了

**Comment by sakurrasama** [comment]
在收藏列表里 那个收藏图标消失了但是你点一下就会取消

**Comment by kayanouriko** [comment]
@sakurrasama 修复了

**Comment by sakurrasama** [comment]
@kayanouriko dalao那个收藏的功能是不是有bug 比如要收藏到favorite3却跑到favorite4

**Comment by kayanouriko** [comment]
@sakurrasama 操作没问题的，可能解析文件夹名字显示的时候有点小问题，今晚回家我再看看这功能，毕竟很久没动过了，可能网站改版了

**Comment by sakurrasama** [comment]
@kayanouriko 还有在收藏列表里面要移动本子到另一个列表也不能移动

**Comment by kayanouriko** [comment]
@sakurrasama 操作没问题的，只是选择了任意收藏夹的时候收藏夹名字的解析有问题导致显示和所得不一致而已，代码已经修正解析问题了。

**Comment by sakurrasama** [comment]
@kayanouriko dalao有些本子会搜不到上网页版就可以搜到 比如黑猫スミス

**Comment by Nekondesu** [comment]
@kayanouriko （...首先感谢老哥在工作忙碌之余，愿意抽出时间完善应用。）
关于“在本子页面里点击标签，进行快速跳转搜索，没有可供操作的搜索栏"功能缺陷的改进建议。

   之前1.3版本，在本子页面里点击那些该本子所含有的标签，是可以快速跳转到画廊搜索页面并自动将该标签填入搜索栏中，搜索所有含该标签之本子，并能后退到原先的本子页面的（描述应该清楚了吧~）
    现我在使用v1.4.1版本，不知道自哪个版本起（中间版本没来得及更新安装），”快速跳转到画廊搜索页面，并自动输入该标签搜索”被更新成了“直接跳转到该标签下所有本子的页面”，而不是跳转到原先的画廊搜索页面。
    带来的不便是，现在这个点击tag跳转后的页面, 没！有！了！可供编辑操作的顶部“搜索栏”，原先的顶部搜索栏处改成了该固定的tag。**于是如果我想在这个页面，向搜索栏中另添加其他tag，进行进一步筛选搜索便不可以了。或者我想从搜索栏中复制这个tag进行其他搜索也不可以了，某些tag拼写复杂，记住并重新拼写输入不是易事。亦或者我想在这个tag搜索页面里，进行一般设定，如画廊类型设置、最低评分更改也不可以了，现加入的高级筛选同理**（大概使用者的操作自由性也随之被削减了233）
附加说明图片：https://i.loli.net/2019/05/08/5cd1cbdfe536d.png
衷心希望作者大大能在v1.4.2中及时更改，其实就是复原原先的顶部搜索栏而已~ 谢谢！
    祝生活愉快！

**Comment by kayanouriko** [comment]
@Asakinb 知道你说的是啥 我在这里也有解释过 https://github.com/kayanouriko/E-HentaiViewer/issues/54#issuecomment-486172670
主要是新版采用了系统标准化搜索控件，之前改版的时候有些不可控问题尚未解决，就直接去除了搜索功能，加之标签搜索这页面这块之后还想加上标签收藏的操作，代码逻辑上也有冲突的地方。
之后我再想想更好的解决方案先把。

**Comment by sakurrasama** [comment]
@kayanouriko  dalao 频率出现网络错误和加载失败 也挂了代理网络没有问题

**Comment by kayanouriko** [comment]
@sakurrasama 网络问题摊手

**Comment by sakurrasama** [comment]
@kayanouriko 网络的话无线很稳定挂不挂代理进去都能看 就是老网络错误和图片加载失败

**Comment by xioxin** [comment]
尽量避免使用日本vpn 部分本子会因为版权问题隐藏掉 

发自我的 iPhone

**Comment by sakurrasama** [comment]
希望在收藏页面也加个翻页功能

**Comment by rainocean** [comment]
能使用cookies登录吗？
有些帐号直接登录进不去里站……

**Comment by kayanouriko** [comment]
@heassa 后续更换swift的时候再做这个

**Comment by xioxin** [comment]
更换swift真是太好了, oc完全看不懂.

**Comment by xioxin** [comment]
会用SwiftUI吗

**Comment by kayanouriko** [comment]
@xioxin swiftUI组件起码两年后才有适应性吧=，=有的等了
这项目oc已经写烂了，趁着换swift再重构一遍，把一些基类再归纳分离开来

**Comment by even-zhang** [comment]
进去总是提示解析错误，等待版本升级T_T

**Comment by zxhzxhz** [comment]
先感谢dalao在工作之余还在一直更新
然后想问下，可否修改一下应用条目在iPad上的布局，使得一页可以显示更多的漫画。本人在用的iPad Pro 9.7是4:3的屏幕比例，每页只能显示两个半漫画条目，而且只是缩略图拉大，中间留有大段空白。
附图：
![197180D5-4CEF-41D0-A308-41EE643C81C8](https://user-images.githubusercontent.com/47572137/60758739-50cc4100-a04d-11e9-9dec-a3b16feaa974.png)

**Comment by kayanouriko** [comment]
@zxhzxhz 这个已经知道了，在1.4.0的版本试图改造iPad版本的UI发现工程量不是一般的大
我已经重新设计过iPad版的界面布局了，详见swift改造计划，估计耗时要久一点，到时候希望项目在视觉和性能上都有比较大的进步

**Comment by zxhzxhz** [comment]
> @zxhzxhz 这个已经知道了，在1.4.0的版本试图改造iPad版本的UI发现工程量不是一般的大
> 我已经重新设计过iPad版的界面布局了，详见swift改造计划，估计耗时要久一点，到时候希望项目在视觉和性能上都有比较大的进步

了解，再次感谢！
