### ISSUE TITLE
反馈一个标签跳转bug.

### ISSUE THREAD

**Issue by Nekondesu** [kayanouriko/E-HentaiViewer#56]
#### 机型 + 系统
例: iph one 7 plus / iOS10.2.6
IPhone8 iOS12.1.2
#### 运行网络环境
例: wifi + 有VPN
WiFi/4G + 自搭的V2ray
#### 具体描述
例: 无法获取画廊列表
在某个本子页面里，点击标签跳转时，偶尔会有程序崩溃现象，重开后恢复正常。（PS,从画廊或者收藏进去本子，进行此操作，偶尔都有崩溃现象发生。
#### 截图
例: ![](图片地址)
应该不需要吧，描述大概够了

**Comment by kayanouriko** [comment]
这个问题可复现，该commit已修复 https://github.com/kayanouriko/E-HentaiViewer/commit/4af2fb98beaba17023878607e9edfd878b3ebd62
ipa未来发布版本更新可修复
