### ISSUE TITLE
=,=自己的新界面

### ISSUE THREAD

**Issue by kayanouriko** [kayanouriko/E-HentaiViewer#6]
列表
新增了几个信息点,大致和安卓的EhViewer还是一样,主要是让人能看出时间,页数和是否有种子下载(虽然应用本身暂不提供下载功能),tag本来也考虑加入,但是加入方法还有待商榷..
列表支持预加载下一页
跳页功能暂时想不到比较好的呈现方法Orz
![](https://ws4.sinaimg.cn/large/006tNc79ly1fgcd13xhgkj30yi1pcb29.jpg)

热门和收藏整合到一个tab页
![](https://ws2.sinaimg.cn/large/006tNc79ly1fgcd0osg2aj30yi1pc4qp.jpg)

搜索新增星级筛选,其余的待加入
tag和作者搜索打算单独抽出,所以这两个筛选感觉实用性不大,现阶段的这两个应该是最常用的了,语言限定估计后面会做成和EhViewer一样
![](https://ws2.sinaimg.cn/large/006tNc79ly1fgcd157cz6j30yi1pc437.jpg)

设置界面暂时没改动,新增网页登陆
![](https://ws4.sinaimg.cn/large/006tNc79ly1fgcd0bm3qcj30yi1pc0zl.jpg)

详情(暂定)
参照app store界面设计
将分划两块
![](https://ws4.sinaimg.cn/large/006tNc79ly1fgcd092ujij30yi1pckjm.jpg) ![](https://ws1.sinaimg.cn/large/006tNc79ly1fgcczh4rg2j30yi1pc7ot.jpg) ![](https://ws2.sinaimg.cn/large/006tNc79ly1fgcczl3xsxj30yi1pck7z.jpg)

看图浏览器
基本逻辑设计好了,加载大量图片的画廊时候的图片解析速度始终和安卓版的有点差距,再给我点时间缕缕

跳转到看图界面→等待从详情url解析出的大图链接→预加载已获取到的大图链接→获取到用户浏览的页数链接时中断下载任务→开始下载对应的大图的任务→当前页大图下载完毕,依次预加载下一页大图→用户跳动页码→中断当前下载任务,转而加载用户跳转页的图片→预加载跳转页下一页的大图

缓存逻辑
对列表,详情,图片都进行缓存,待处理

主要是整体看上去更加符合iOS的设计风格[审美废路过

**Comment by stu43005** [comment]
新介面不錯 先推個(￣▽￣)ノ

**Comment by xioxin** [comment]
详情页标签在哪里？

**Comment by kayanouriko** [comment]
@xioxin 详情页标签下属内容依次是:预览-TAG(标签)-画廊信息-类似画廊-上传者其他上传作品

**Comment by xioxin** [comment]
新界面试了 :+1: 苹果下果然还是这种界面比较适合
希望增加收藏tag的功能

**Comment by kayanouriko** [comment]
@xioxin 还有很多需要改进的地方,无论是代码还是界面Orz,特别是看图界面,只怪自己技术太渣了
tag肯定是要加的,让我想想怎么处理好先

**Comment by xioxin** [comment]
我进入到看图界面没有返回按钮:joy: 
话说我会swift 但是不怎么懂ui 懂php和web前端 有没有能不能帮上忙的 :joy:

**Comment by kayanouriko** [comment]
@xioxin 一样的UI审美废路过,只会模仿别人的.
你可以swift自己写一个啊,你还会web,解析起来应该比我好多了...
你写个好用的我就吃现成饭了

**Comment by xioxin** [comment]
我不是审美啦 cocoaTouch框架直接不懂 根本不会 做不了ui 但是语法没有问题
以前和别人合作写东西 我只写过数据层 视图控制器别人写 导致我现在还不会ui

**Comment by kayanouriko** [comment]
=,=还有这种操作,不过框架这东西用一个学一个也很快的
