### ISSUE TITLE
了解到了一条E站可能停运情况

### ISSUE THREAD

**Issue by Nekondesu** [kayanouriko/E-HentaiViewer#62]
我这边梯子有点问题，进不去论坛。想把这个信息传递给您，信息真实性实在抱歉，我没法去验证，希望对日后开发抉择有帮助。
![847368B7-7875-4253-8822-326D4B68DD02](https://user-images.githubusercontent.com/42878282/61925707-14329c00-afa0-11e9-8b34-ad7dae1ecdae.jpeg)

**Comment by xioxin** [comment]
现在已经关闭了

**Comment by Nekondesu** [comment]
@xioxin 没想到又暂时复活了
