### ISSUE TITLE
大佬 能上架expo  这样就不用上架 就可用试用了

### ISSUE THREAD

**Issue by DevCoz** [kayanouriko/E-HentaiViewer#65]
#### 机型 + 系统
例: iphone 7 plus / iOS10.2.6

#### 运行网络环境
例: wifi + 有VPN

#### 具体描述
例: 无法获取画廊列表

#### 截图
例: ![](图片地址)

**Comment by ChihayaK** [comment]
https://expo.io/terms
建议读一下，明确说了不可以的。

**Comment by DevCoz** [comment]
> https://expo.io/terms
> 建议读一下，明确说了不可以的。

好的
