### ISSUE TITLE
有赛钱箱吗

### ISSUE THREAD

**Issue by ljyloo** [kayanouriko/E-HentaiViewer#66]
做得很不错呀。比Dai-Hentai功能丰富太多了
只是单纯想感谢一下作者
加油

**Comment by kayanouriko** [comment]
感谢赞赏，其实看代码的话就感觉写的很烂了，我自己重写之后感觉各方面都好上不少
感觉沾上钱项目维护的理由就没那么纯粹了，自己更新也不是很快，所以就不贴了
