### ISSUE TITLE
关于iphone se的安装问题

### ISSUE THREAD

**Issue by kvassmacncheese** [kayanouriko/E-HentaiViewer#67]
我试着在a9的iphone se上安装eh，但是却显示“unable to install“EH”
请问有什么解决方式。。。

**Comment by kayanouriko** [comment]
系统版本？安装方式？
应用最低系统要求iOS11

**Comment by kvassmacncheese** [comment]
IOS 13

**Comment by kvassmacncheese** [comment]
系统版本13.1.2，A1662。求救！

**Comment by kayanouriko** [comment]
爱莫能助了摊手，可以尝试自己编译项目

**Comment by kvassmacncheese** [comment]
是因为系统太新的缘故吗？还是因为机型适配？

**Comment by kayanouriko** [comment]
正常来说和机型系统没关系，不清楚那个自签名应用，摊手

**Comment by kvassmacncheese** [comment]
自签名应用是什么呀站长？

**Comment by kvassmacncheese** [comment]
哦还有，appbuild1和appbuild2有什么区别呀？

**Comment by kvassmacncheese** [comment]
请问一下，eh build1和eh build2有什么区别呀？
