### ISSUE TITLE
你好，请问能否加入导出的功能？或者提供局域网内通过url下载app中已下载的本子呢？

### ISSUE THREAD

**Issue by weiailuxueqi** [kayanouriko/E-HentaiViewer#68]
#### 机型 + 系统
iphone XsMax / iOS13

**Comment by kayanouriko** [comment]
目前版本有分享功能，支持分享画廊链接
未来版本支持已缓存画廊导出到文件App的功能
有时间研究H@H机制的话，会加入app下载画廊的功能

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
