### ISSUE TITLE
Darkmode下字體變白色導致什麼內容都看不到

### ISSUE THREAD

**Issue by r20019xx** [kayanouriko/E-HentaiViewer#69]
#### 机型 + 系统
iphone xr / iOS13.1.3

#### 运行网络环境
wifi

#### 具体描述
如題 連設定頁面皆為一片全白

#### 截图
https://upload.cc/i1/2019/10/25/wYMBop.png

**Comment by kayanouriko** [comment]
新版本会适配darkmode
