### ISSUE TITLE
复制画册种子的磁力链

### ISSUE THREAD

**Issue by xioxin** [kayanouriko/E-HentaiViewer#7]
比如 https://exhentai.org/g/1069647/ffb1900549/ 
这是种子地址
 https://ehtracker.org/get/1069647/97f06f8373171c41c1233c4683ee7187cf0cb518.torrent
后半部分加上磁力链头就可以了 
magnet:?xt=urn:btih:97f06f8373171c41c1233c4683ee7187cf0cb518

希望可以增加这个功能 方便复制到小米路由之类的远程下载器中下载

**Comment by kayanouriko** [comment]
没考虑NAS的情况=3=
这个可以有的说~

**Comment by kayanouriko** [comment]
已添加
![](https://ws2.sinaimg.cn/large/006tKfTcly1fgeyqkeq75j30yi1pcwhv.jpg)
![](https://ws4.sinaimg.cn/large/006tKfTcly1fgeyqixkcsj30yi1pc41m.jpg)

**Comment by xioxin** [comment]
谢谢大佬 👍

**Comment by xioxin** [comment]
话说最新版在哪里下载 主分支都是数月前的

**Comment by kayanouriko** [comment]
@xioxin 没开分支,我整个项目重写了,还没上传,我炸一次尸你别太兴奋,都是零零碎碎时间写的

**Comment by xioxin** [comment]
oc 还是 swift ？
