### ISSUE TITLE
阅读器下载地址在哪里呀萌新求解答

### ISSUE THREAD

**Issue by 646299775** [kayanouriko/E-HentaiViewer#71]
#### 机型 + 系统
例: iphone 7 plus / iOS10.2.6

#### 运行网络环境
例: wifi + 有VPN

#### 具体描述
例: 无法获取画廊列表

#### 截图
例: ![](图片地址)

**Comment by kayanouriko** [comment]
https://github.com/kayanouriko/E-HentaiViewer/releases
