### ISSUE TITLE
点击本子闪退

### ISSUE THREAD

**Issue by zsy1314** [kayanouriko/E-HentaiViewer#72]
#### 机型 + 系统
iphone XR / iOS13.1.1

#### 运行网络环境
wifi + SSR

#### 具体描述
APP启动正常，登录正常（夜间模式设置页面没有内容），各种热门、收藏之类的列表都可以正常显示，但是点击任意本子立刻闪退。
连接xCode使用Run的情况下，点击本子不会闪退，但是App彻底卡住不动。因为连接着xCode调试，所以有一些信息，见下面两个截图。
第1个是启动App什么都没有操作。
第2个是点击本子卡死之后。

#### 截图
![截屏2019-11-17下午10 59 32](https://user-images.githubusercontent.com/7313100/69009222-5ee08580-098e-11ea-9306-a9ae4c9abcbd.png)
![截屏2019-11-17下午10 59 53](https://user-images.githubusercontent.com/7313100/69009224-62740c80-098e-11ea-8fe9-50bb027f775e.png)

**Comment by kayanouriko** [comment]
你的Xcode应该是11.2的版本，请更新你的Xcode，这是个Xcode的BUG。
