### ISSUE TITLE
希望加入缓存功能

### ISSUE THREAD

**Issue by glm9412** [kayanouriko/E-HentaiViewer#73]
希望作者大大能加入缓存功能，tag显示在列表页真的是个非常棒的功能，比EH需要点进去才能看到，效率高太多了

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by kayanouriko** [comment]
画廊缓存功能是有的，看过的就自动缓存了
后面应该会整个应用都缓存了，减少爬虫次数

**Comment by glm9412** [comment]
呃，是我描述不准确，指的是整篇下载的功能

**Comment by kayanouriko** [comment]
技术太渣了，我还没弄懂H@H的原理，我应该不会加入这个功能。
你可以使用专门做这事的python程序或者别的
目前客户端提供了复制磁力链接和隔空投送画廊链接的功能，配合已读画廊自动缓存功能。
未来如果我弄懂了H@H机制，可以加入基于H@H的下载功能

**Comment by glm9412** [comment]
好的，感谢回答！
