### ISSUE TITLE
安装 问题

### ISSUE THREAD

**Issue by VVVVictorJ** [kayanouriko/E-HentaiViewer#74]
#### 机型 + 系统
iphone 7 plus / iOS12.3.1

#### 运行网络环境
wifi + 有VPN

#### 具体描述
impactor 无法安装，
Fix Provision.cpp:71 
#### 截图
![image](https://user-images.githubusercontent.com/38826071/72661512-efcaf000-3a15-11ea-921b-49af303e6d1a.png)

**Comment by kayanouriko** [comment]
impactor问题无能为力，摊手

**Comment by VVVVictorJ** [comment]
@kayanouriko 我看下saurik的推文，意思是如果有苹果开发者账号的cydia还可以继续用。
他还说12月中之前没有办法解决得了。
现在看来只能用虚拟机装了。

**Comment by kayanouriko** [comment]
@VVVVictorJ 现在iPhone X及以下支持无条件JB，你可以选择JB

**Comment by VVVVictorJ** [comment]
@kayanouriko JB手机被黑就不好了，还是vm黑苹果算了
