### ISSUE TITLE
EX站点解析失败

### ISSUE THREAD

**Issue by Nekondesu** [kayanouriko/E-HentaiViewer#75]
![A816DD4E-E5BE-4ED3-9C6B-305611C80DC5](https://user-images.githubusercontent.com/42878282/74092343-587d2800-4afd-11ea-83d4-b07e9813ce06.png)
#### 机型 + 系统
例: iphone 7 plus / iOS10.2.6

#### 运行网络环境
例: wifi + 有VPN

#### 具体描述
例: 无法获取画廊列表

#### 截图
例: ![](图片地址)

**Comment by Nekondesu** [comment]
抱歉，手机浏览器莫名发不了细文，在此补充说明。
切换EX站点后，获取不了画廊列表，并无法获取更新收藏夹，并提示“解析失败”。
iPhone8 iOS12.2.1 
Wifi+4G+V2/SSR
![313079EB-9B74-4BA1-AAEF-29D287ACC30C](https://user-images.githubusercontent.com/42878282/74092395-11436700-4afe-11ea-993a-239a5ee06543.png)

**Comment by kayanouriko** [comment]
自己参照wiki看一下原因，一个是账号或者vpn站点的问题

等新版上了支持导出解析日志的时候我才方便帮你们看原因所在

**Comment by Nekondesu** [comment]
感谢，已解决
