### ISSUE TITLE
是否考虑汉化标签？

### ISSUE THREAD

**Issue by xioxin** [kayanouriko/E-HentaiViewer#8]
https://github.com/Mapaler/EhTagTranslator
数据都写在这个项目的wiki里面
通过他的浏览器插件可以获取到json版本

**Comment by kayanouriko** [comment]
这个要实现在线更新数据库还是要解析wiki,暂时做个离线版的数据库倒是可以
我现在基础版的功能还不是很健全T T

**Comment by xioxin** [comment]
离线就好

**Comment by kayanouriko** [comment]
[https://ws4.sinaimg.cn/large/006tKfTcgy1fi32uktvbtj30yi1pcwyx.jpg](https://ws4.sinaimg.cn/large/006tKfTcgy1fi32uktvbtj30yi1pcwyx.jpg) 
[https://ws2.sinaimg.cn/large/006tKfTcgy1fi32uibe5uj30yi1pcjwe.jpg](https://ws2.sinaimg.cn/large/006tKfTcgy1fi32uibe5uj30yi1pcjwe.jpg) 

目前暂时是做成这样的,支持中文和罗马音搜索tag,设置有开关是否显示汉化标签,感谢项目和xioxin你的辛勤汉化~(*^__^*) 
等版本更新的时候再去你们那边申请一下数据库的使用

**Comment by OpportunityLiu** [comment]
现在有持续集成发布的json版本了

https://github.com/EhTagTranslation/Database/releases

**Comment by kayanouriko** [comment]
@OpportunityLiu 我嬲，swift重构最先写的就是去爬他们的md数据库

**Comment by OpportunityLiu** [comment]
这功能优先级这么高的吗……
我应该早早给每个使用数据库的人发一下

**Comment by OpportunityLiu** [comment]
说明文档在这里 
https://github.com/EhTagTranslation/Database/wiki/%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97

**Comment by kayanouriko** [comment]
@OpportunityLiu 因为开始没提供json版啊，其他的逻辑其实都还好做，所以一开始就先动手做这个了。
自己做的要解析好几个页面，耗时也久，有这个json版舒服多了
啊啊我半个月的业余时间白费了。。

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/63637257-2c83fc80-c6ad-11e9-8494-f8152421aaaa.png)
所以说要关注下上游啊，我们2月份就开始讨论这个事情了，4月新的这一套就差不多搞完了，最近是把旧的数据库archive了。我看你的这个项目最近没啥更新，所以就没提醒你。。。

**Comment by OpportunityLiu** [comment]
https://github.com/Mapaler/EhTagTranslator/issues/50
https://github.com/Mapaler/EhTagTranslator/issues/57

**Comment by kayanouriko** [comment]
上班狗体谅一下，基本盯着自己需求满足就不怎么关注了
主要是业余重写swift版慢，这项目能用就不更新了

**Comment by OpportunityLiu** [comment]
之前有跟hippo说过，不过他不太积极（现在直接把EhViewer都Archive了），所以有点受打击。
还是应该也跟你们说一声的，是我的锅。

**Comment by kayanouriko** [comment]
毕竟爱发电，站子也说不准突然就没了，H大也维护了那么多年了，谅解谅解。

**Comment by OpportunityLiu** [comment]
添加标签翻译我们都做了个App，现在也不用去编辑md了
https://ehtagtranslation.github.io/Editor

**Comment by OpportunityLiu** [comment]
> 上班狗体谅一下，基本盯着自己需求满足就不怎么关注了
> 主要是业余重写swift版慢，这项目能用就不更新了

只是有点心疼你。。。

**Comment by kayanouriko** [comment]
@OpportunityLiu 没事，这项目本来就上不了架，基本是自用的，没啥心疼不心疼
