### ISSUE TITLE
请教如何使用应用内“关注栏”

### ISSUE THREAD

**Issue by Nekondesu** [kayanouriko/E-HentaiViewer#84]
#### 具体描述
请问关注栏如何使用，都能关注些哪些内容-如“上传者”，去哪里才能添加“关注”

(真的有在翻阅Wiki和Issue了- -，也去了下E站Web找“关注”相关，但没有找到答案）

顺便十分感谢作者有在更新 Kora！
#### 截图
[我是图](https://pics.images.ac.cn/image/5ecaaf5dbf966.html)

**Comment by kayanouriko** [comment]
关注功能为网站的watched模块，用于追踪关注的标签，对应My Tags，在设置-我的标签里面设置

**Comment by Nekondesu** [comment]
> 关注功能为网站的watched模块，用于追踪关注的标签，对应My Tags，在设置-我的标签里面设置

感谢！那“Hidden”标签，就是对应了“屏蔽”功能对吗
