### ISSUE TITLE
开发进度以及水楼

### ISSUE THREAD

**Issue by kayanouriko** [kayanouriko/E-HentaiViewer#9]
网站的设置比我自己解析来得轻松好多
来源这里:/uconfig.php

1. 主要跟进安卓版的功能
    - Gallery Name Display 标题日英文切换
    - Front Page Settings 列表详情和缩略图呈现，热门画廊呈现，分类屏蔽
    - Tag Namespaces 搜索中排除标签组
    - Excluded Languages 列表和搜索排除语言
    
2. 收藏优化
    包括收藏夹的选择，现有收藏操作逻辑中被隐藏的部分

3. tag的中文化
    主项目的含有html较难解析，已找到一个改进版的json，待跟进

4. 界面的优化

我们下一3个月见，米娜桑马达捏~

**Comment by codexss** [comment]
希望可以添加一个类似书签功能
https://exhentai.org/g/1076048/42cf356bf6/
像这种长篇……

**Comment by kaiwwww** [comment]
一定需要越狱吗

**Comment by xioxin** [comment]
可以不越狱 参考 #1

**Comment by SiliciumnFairy** [comment]
我想反馈一下，IP6SP IOS10.3.2(14F89)下线上收藏夹无法载入图片的问题

**Comment by kayanouriko** [comment]
@Y-Schrodinger 无法载入图片具体是什么情况?
目前显示在当前屏幕的画廊有一定概率不会出封面,你滚动一下或者再次刷新就好了=,=

**Comment by SiliciumnFairy** [comment]
@kayanouriko https://drive.google.com/file/d/0B5woOofnXfa7bEJaenBYSHJSNGM/view?usp=sharing 大概是这样的
还有新发现了一个bug，点开标签快速搜索中的标签，取消收藏后再收藏的话，程序会crash

**Comment by kayanouriko** [comment]
@Y-Schrodinger 你那个是老版的应用了=,=这个老版我已经不在维护了,你可以尝试一下我的重构后的应用

**Comment by SiliciumnFairy** [comment]
@kayanouriko 好的，感谢dalao！

**Comment by kayanouriko** [comment]
![](https://ws4.sinaimg.cn/large/006tNc79gy1flbltdy6hmj30yi1pcdqv.jpg)
https://ws4.sinaimg.cn/large/006tNc79gy1flbltdy6hmj30yi1pcdqv.jpg

新的搜索,基本同步了网站的功能,标签跳转都跳这个页面,查看标签的时候有更加自由的操作了,图片上传那个看这个月的版本有没有时间做吧..

不知道有聚聚愿意跟我一起开发么?水平还是太次了...

**Comment by xioxin** [comment]
可惜不会oc  :joy:

**Comment by kayanouriko** [comment]
下个计划是彻底适配ipad和加入缓存...
国内下载大图太不稳了,现在的方式很容易出现解析问题,图片浏览器还需要重新编写...自己功力好渣啊...
ps:我再也不敢改界面了....

**Comment by xioxin** [comment]
我更新了最新的版本 遇到了一些问题
* 中文标签开关为灰色 无法打开
* 面部识别/指纹解锁 重启应用后会自动关闭
* 搜索在所有类型全选的情况 doujinshi 搜不到 单独选择 doujinshi 就不会有问题 直接点击标签打开的搜索不会有问题 

顺便推荐你个本地的漫画软件 是我用过ios下漫画阅读器做的最好的一个 
https://itunes.apple.com/cn/app/comicglass-comicreader/id363992049?mt=8
还可以访问局域网smb共享 不过是付费软件 软件总共30块钱 也不是很贵

**Comment by kayanouriko** [comment]
@xioxin 
1. 中文标签功能由于我并入缓存功能的时候受到波及所以暂时屏蔽了,更新日志里面有说
2. X么?我7p正常使用保护功能,由于没有机子测试,这个估计gg了...
3. 已修复,就不发包了...这个搜索是直接网站逻辑控制的,搜索效果有待验证...

单纯的离线看图浏览逻辑其实蛮简单的
但是由于网站解析图片和对朝网络的特殊性,加上我代码能力太差了,网站图片解析和请求逻辑这一块写了好几次效果都不怎么样,最终我用了一种比较取巧的方式呈现图片,导致在看图操作的体验不佳...Orz

**Comment by xioxin** [comment]
阅读器翻页的时候经常跳页 一次翻两页 可能是滑动和单击同时触发了 
话说接受打赏吗? 原本打算参与开发的 但是oc我实在是无力啊

**Comment by xioxin** [comment]
还有一个上架的可以访问 E站EX站N站的app
https://itunes.apple.com/cn/app/the-manga/id1089887918?mt=8
价格有些贵

**Comment by kayanouriko** [comment]
嗯,这个算遗留问题了,为了借用webview控件的一些功能,我把手势响应链传递下去了...
图片浏览器这一块后面肯定还要改的,这个浏览器目前只是勉强可用的状态...
这应用需要修修补补的细节和功能还蛮多...

打赏算了,这个会约束人的,弄得蛮不舒服的,应用肯定会继续做的,毕竟我自己也在用[滑稽

上架事情的之前我就说过了,苹果逃避审核太累了,我这应用一开始就基本是自我需求而诞生的2333,丢个git上面就好了...

**Comment by xioxin** [comment]
我曾经有个想法 是做一个通用的漫画阅读器 网站内容解析通过JavaScriptCore 来加载js外部脚本来解析 实现模块化 app提供几套ui模板 再实现一个本地阅读器的功能 然后上架 😂  但是自己功力有限 也就想想

**Comment by bes1355** [comment]
想问下 搜索页面和主站不是很同步是为什么...

**Comment by kayanouriko** [comment]
@bes1355 我自己测试过搜索结果和网页版是完全一致
客户端和网站搜索逻辑有几处地方要值得注意的
1. 在有账号的情况下,确保你的高级设置里面的设置和网站是否一致,这个会影响你搜索的结果,其中语言排除这一项,客户端是可以完全排除日语原版的,而网站是不能排除的
2. 客户端的搜索设置是有缓存的,也就是你选过排除低分之类的设置,下次打开应用也会记住的,而网站则是每次都重置你的搜索设置
仔细检查一下以上两点应该是得出来的结果是一致的

**Comment by bes1355** [comment]
@kayanouriko 那应该是我的问题，同样搜索Chinese，同样的标签选择，手机版出来的结果会比电脑版的每页少那么几本，我去试试缓存删了看看。

**Comment by xioxin** [comment]
@bes1355 检查一下你是不是开了日本的代理 因为一些版权问题 日本ip有些资源会隐藏掉

**Comment by bes1355** [comment]
@xioxin 挂了HK的代理. 我有2个IOS的EH 一个是那个Dai-hentai 那个没问题。

**Comment by bes1355** [comment]
尝试多遍无果...
站点选的是EX
客户端排除语言也没开启
不管是挂不挂代理 都无法搜出完整结果...难受 隔壁Dai没问题也不太清楚什么情况。

**Comment by kayanouriko** [comment]
@bes1355 少了几本?一页25条数据,我对了一下我的第一页和第二页数据都和网页版一样,你把你的搜索参数发出来看一下呗

**Comment by bes1355** [comment]
@kayanouriko 
[https://user-images.githubusercontent.com/22226025/33916120-443ade6a-dfe2-11e7-9e4d-470b3d107dda.PNG](https://user-images.githubusercontent.com/22226025/33916120-443ade6a-dfe2-11e7-9e4d-470b3d107dda.PNG)
[https://user-images.githubusercontent.com/22226025/33915976-6c906796-dfe1-11e7-97b7-0af25ff12f16.png](https://user-images.githubusercontent.com/22226025/33915976-6c906796-dfe1-11e7-97b7-0af25ff12f16.png)
[https://user-images.githubusercontent.com/22226025/33915977-6e16a09e-dfe1-11e7-8b3c-0bd07a3143cb.png](https://user-images.githubusercontent.com/22226025/33915977-6e16a09e-dfe1-11e7-8b3c-0bd07a3143cb.png)


不知道露点会不会违规..懒得打MA了.. 如图所示 基本2 3本之间就会空个1 2本有时候甚至3 4本。

**Comment by kayanouriko** [comment]
@bes1355 
哦哦哦,记起来了,新包发布之后 @xioxin 提了个搜索的bug,我修复了但是没有更新安装包=,=是这个bug造成的...
你是安装包安装的话确实有问题...=,=
抱歉让你折腾了那么久...

**Comment by bes1355** [comment]
好的..待会我重下一个

**Comment by kayanouriko** [comment]
@bes1355 我修复包没放上来...打算等下次更新一起打包

**Comment by bes1355** [comment]
@kayanouriko ...好的 大概什么时候更新  我好重下个

**Comment by kayanouriko** [comment]
一月份吧2333

**Comment by bes1355** [comment]
1月份 我觉得还行

**Comment by fengzeyan** [comment]
等车的时间修改了一下用webview加载图片的方式 ，改成了uiimageview和uiscrollview。 XD

//
//  QJMangaItem.m
//  testImageView
//
//  Created by QinJ on 2017/5/4.
//  Copyright © 2017年 kayanouriko. All rights reserved.
//

#import "QJMangaItem.h"
#import "QJBigImageItem.h"
#import <WebKit/WebKit.h>
#import <YYWebImage/UIImageView+YYWebImage.h>

@interface QJMangaItem () <UIScrollViewDelegate, WKNavigationDelegate, UIGestureRecognizerDelegate>

@property(nonatomic, strong) UIActivityIndicatorView *activity;
@property(nonatomic, strong) UIView *bgView;
//@property (nonatomic, strong) WKWebView *webView;
@property(nonatomic, strong) UIImageView *imgView;
@property(nonatomic, strong) UIScrollView *scrollView;

@property(nonatomic, strong) UIProgressView *progress;
@property(nonatomic, strong) UITapGestureRecognizer *tapGes;
@property(nonatomic, strong) UITapGestureRecognizer *tapGes1;
@property(nonatomic, strong) UILongPressGestureRecognizer *longGes;
@property(nonatomic, strong) QJBigImageItem *item;

@end

@implementation QJMangaItem

- (instancetype)init {
    self = [super init];
    if (self) {
        [self customInit];
    }
    return self;
}

- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (self) {
        self.userInteractionEnabled = YES;
        [self customInit];
    }
    return self;
}

- (void)customInit {
//    [self addSubview:self.webView];
//    [self addSubview:self.bgView];
//    [self addSubview:self.progress];
//    [self addSubview:self.activity];
    [self.scrollView addSubview:self.imgView];
    [self addSubview:self.scrollView];

}

- (void)refreshItem:(QJBigImageItem *)item {
    self.imgView.image = [UIImage imageNamed:@"LOGO"];
    self.bgView.alpha = 1;
    [self.activity startAnimating];
    self.item = item;
    [item getReallyImageUrl:^(NSString *url) {
        YYWebImageManager *manager = [YYWebImageManager sharedManager];
        YYImageCache *cache = manager.cache;
        UIImage *targetImage = [cache getImageForKey:item.realImageUrl];
        if (targetImage) {
            [self configImageForItem:targetImage];
        } else {
            [manager requestImageWithURL:[NSURL URLWithString:item.realImageUrl] options:YYWebImageOptionAllowBackgroundTask progress:nil transform:nil completion:^(UIImage *image, NSURL *url1, YYWebImageFromType from, YYWebImageStage stage, NSError *error) {
                if (self.item.realImageUrl == item.realImageUrl) {
                    [self configImageForItem:image];
                }
                [cache setImage:image forKey:item.realImageUrl];
            }];
        }
    }];
}


- (void)configImageForItem:(UIImage *)img {
    CGFloat bl = UIScreenWidth() / UIScreenHeight();
    CGFloat imgbl = img.size.width / img.size.height;
    dispatch_async(dispatch_get_main_queue(), ^{
        if (bl > imgbl) {
//宽度百分百
            CGFloat height = UIScreenWidth() * img.size.height / img.size.width;
            self.imgView.frame = CGRectMake(0, 0, UIScreenWidth(), height);
            self.scrollView.contentSize = CGSizeMake(UIScreenWidth(), height);
        } else {
            //高度百分百
            self.imgView.frame = CGRectMake(0, 0, UIScreenWidth(), UIScreenHeight() - 20);
            self.scrollView.contentSize = CGSizeMake(UIScreenWidth(), UIScreenHeight() - 20);
        }
        self.imgView.image = img;
    });


}

#pragma mark -创建一个本地离线html

- (NSString *)getHtmlWithUrl:(NSString *)url x:(NSString *)x y:(NSString *)y {
    CGFloat bl = UIScreenWidth() / UIScreenHeight();
    CGFloat imgbl = [x floatValue] / [y floatValue];
    NSString *css = @"";
    if (bl > imgbl) {
        css = @"height:100%;";
    } else {
        css = @"width:100%;";
    }
    NSString *html = [NSString stringWithFormat:@"<!DOCTYPE html>\
                      <html>\
                      <head>\
                      <meta charset=\"utf-8\" />\
                      <title></title>\
                      <style>\
                      div {\
                        display: flex;\
                        justify-content: center;\
                      }\
                      img {\
                        %@\
                        position: absolute;\
                        left: 0;\
                        top: 0;\
                        right: 0;\
                        bottom: 0;\
                        margin: auto;\
                      }\
                      </style>\
                      </head>\
                      <body>\
                      <div>\
                      <img src=\"%@\" />\
                      </div>\
                      </body>\
                      </html>", css, url];
    return html;
}

#pragma mark -UIScrollViewDelegate

- (void)scrollViewWillBeginZooming:(UIScrollView *)scrollView withView:(UIView *)view {
    if (self.delegate != nil && [self.delegate respondsToSelector:@selector(changeWillBegin)]) {
        [self.delegate changeWillBegin];
    }
}

- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView {
    if (self.delegate != nil && [self.delegate respondsToSelector:@selector(changeWillBegin)]) {
        [self.delegate changeWillBegin];
    }
}

#pragma mark -WKNavigationDelegate

- (void)webView:(WKWebView *)webView didFinishNavigation:(null_unspecified WKNavigation *)navigation {
    [self hiddenSomething];
}

- (void)webView:(WKWebView *)webView didFailNavigation:(WKNavigation *)navigation withError:(NSError *)error {
    [self hiddenSomething];
}

- (void)hiddenSomething {
    [self.activity stopAnimating];
    [UIView animateWithDuration:0.5f animations:^{
        self.bgView.alpha = 0;
    }];
}

#pragma mark -懒加载
//- (WKWebView *)webView {
//    if (nil == _webView) {
//        _webView = [[WKWebView alloc] initWithFrame:CGRectMake(0, 0, UIScreenWidth(), UIScreenHeight() - 20)];
//        _webView.scrollView.delegate = self;
//        [_webView addGestureRecognizer:self.tapGes];
//        [_webView addGestureRecognizer:self.longGes];
//
//        //禁止长按弹出 UIMenuController 相关
//        //禁止选择 css 配置相关
//        NSString*css = @"body{-webkit-user-select:none;-webkit-user-drag:none;}";
//        //css 选中样式取消
//        NSMutableString *javascript = [NSMutableString string];
//        [javascript appendString:@"var style = document.createElement('style');"];
//        [javascript appendString:@"style.type = 'text/css';"];
//        [javascript appendFormat:@"var cssContent = document.createTextNode('%@');", css];
//        [javascript appendString:@"style.appendChild(cssContent);"];
//        [javascript appendString:@"document.body.appendChild(style);"];
//        [javascript appendString:@"document.documentElement.style.webkitUserSelect='none';"];//禁止选择
//        [javascript appendString:@"document.documentElement.style.webkitTouchCallout='none';"];//禁止长按
//        //javascript 注入
//        WKUserScript *noneSelectScript = [[WKUserScript alloc] initWithSource:javascript injectionTime:WKUserScriptInjectionTimeAtDocumentEnd forMainFrameOnly:YES];
//        WKUserContentController *userContentController = [WKUserContentController new];
//        [userContentController addUserScript:noneSelectScript];
//        WKWebViewConfiguration *configuration = [WKWebViewConfiguration new];
//        configuration.userContentController = userContentController;
//
//        //控件加载
//        [_webView.configuration.userContentController addUserScript:noneSelectScript];
//        [_webView addObserver:self forKeyPath:@"estimatedProgress" options:NSKeyValueObservingOptionNew context:nil];
//
//        _webView.navigationDelegate = self;
//    }
//    return _webView;
//}

- (UIImageView *)imgView {
    if (nil == _imgView) {
        _imgView = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, UIScreenWidth(), UIScreenHeight() - 20)];
        _imgView.userInteractionEnabled = YES;
        _imgView.contentMode = UIViewContentModeScaleAspectFit;
        [_imgView addGestureRecognizer:self.tapGes];
    }
    return _imgView;
}


- (UIScrollView *)scrollView {
    if (nil == _scrollView) {
        _scrollView = [[UIScrollView alloc] initWithFrame:CGRectMake(0, 0, UIScreenWidth(), UIScreenHeight() - 20)];
    }
    return _scrollView;
}

#pragma mark -进度条监听

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSString *, id> *)change context:(void *)context {
    if ([keyPath isEqualToString:@"estimatedProgress"]) {
        self.progress.progress = [change[@"new"] floatValue];
        self.progress.hidden = self.progress.progress >= 1;
    } else {
        [super observeValueForKeyPath:keyPath ofObject:object change:change context:context];
    }
}

- (UIProgressView *)progress {
    if (!_progress) {
        _progress = [[UIProgressView alloc] initWithFrame:CGRectMake(0, 0, UIScreenWidth(), 2)];
        _progress.progress = 0;
        _progress.trackTintColor = [UIColor clearColor];
    }
    return _progress;
}

- (UITapGestureRecognizer *)tapGes {
    if (!_tapGes) {
        _tapGes = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(singleTapGestureAction:)];
        _tapGes.delegate = self;
    }
    return _tapGes;
}

- (UITapGestureRecognizer *)tapGes1 {
    if (!_tapGes1) {
        _tapGes1 = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(singleTapGestureAction:)];
        _tapGes1.delegate = self;
    }
    return _tapGes1;
}

- (UILongPressGestureRecognizer *)longGes {
    if (!_longGes) {
        _longGes = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:@selector(longPressGestureAction:)];
        _longGes.delegate = self;
    }
    return _longGes;
}

#pragma mark -手势连续响应, wkwebview自带手势, 需要执行这个

- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    return YES;
}

- (void)longPressGestureAction:(UILongPressGestureRecognizer *)longGres {
    if (longGres.state == UIGestureRecognizerStateBegan) {
        UIAlertController *alertVC = [UIAlertController alertControllerWithTitle:@"提示" message:@"确定刷新该图片?" preferredStyle:UIAlertControllerStyleAlert];
        UIAlertAction *cancelBtn = [UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil];
        [alertVC addAction:cancelBtn];
        UIAlertAction *okBtn = [UIAlertAction actionWithTitle:@"好的" style:UIAlertActionStyleDefault handler:^(UIAlertAction *_Nonnull action) {
//            [self.webView loadHTMLString:[self getHtmlWithUrl:self.item.realImageUrl x:self.item.x y:self.item.y] baseURL:nil];
        }];
        [alertVC addAction:okBtn];
        [[self viewController] presentViewController:alertVC animated:YES completion:nil];
    }
}

- (UIViewController *)viewController {
    for (UIView *next = [self superview]; next; next = next.superview) {
        UIResponder *nextResponder = [next nextResponder];
        if ([nextResponder isKindOfClass:[UIViewController class]]) {
            return (UIViewController *) nextResponder;
        }
    }
    return nil;
}

- (void)singleTapGestureAction:(UITapGestureRecognizer *)tapGes {
    CGPoint touchPoint = [tapGes locationInView:self];
    CGFloat width = UIScreenWidth() / 3.f;
    CGFloat height = UIScreenHeight() / 3.f;
    //中心区域
    CGRect midRect = CGRectMake(width, height, width, height);
    //上一页区域
    CGRect leftRect1 = CGRectMake(width, 0, width, height);
    CGRect leftRect2 = CGRectMake(0, 0, width, UIScreenHeight());
    //下一页的区域
    CGRect rightRect1 = CGRectMake(width, height * 2, width, height);
    CGRect rightRect2 = CGRectMake(width * 2, 0, width, UIScreenHeight());

    if (CGRectContainsPoint(midRect, touchPoint)) {
        if (self.delegate != nil && [self.delegate respondsToSelector:@selector(tapInWebView)]) {
            [self.delegate tapInWebView];
        }
    } else if (CGRectContainsPoint(leftRect1, touchPoint) || CGRectContainsPoint(leftRect2, touchPoint)) {
        //上一页
        if (self.delegate != nil && [self.delegate respondsToSelector:@selector(forwardPage)]) {
            [self.delegate forwardPage];
        }
    } else if (CGRectContainsPoint(rightRect1, touchPoint) || CGRectContainsPoint(rightRect2, touchPoint)) {
        //下一页
        if (self.delegate != nil && [self.delegate respondsToSelector:@selector(nextPage)]) {
            [self.delegate nextPage];
        }
    }
}

#pragma mark -getter

- (UIActivityIndicatorView *)activity {
    if (nil == _activity) {
        _activity = [[UIActivityIndicatorView alloc] initWithFrame:CGRectMake(UIScreenWidth() / 2 - 10, UIScreenHeight() / 2 - 10, 20, 20)];
        _activity.activityIndicatorViewStyle = UIActivityIndicatorViewStyleGray;
        _activity.hidesWhenStopped = YES;
    }
    return _activity;
}

- (UIView *)bgView {
    if (nil == _bgView) {
        _bgView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, UIScreenWidth(), UIScreenHeight())];
        _bgView.backgroundColor = [UIColor whiteColor];
        _bgView.userInteractionEnabled = YES;
        [_bgView addGestureRecognizer:self.tapGes1];
    }
    return _bgView;
}

- (void)dealloc {
//    [self.webView removeObserver:self forKeyPath:@"estimatedProgress"];
}

@end

**Comment by fengzeyan** [comment]
写的比较匆忙，可能会导致图片多次缓存以及读取缓存的时候耗时较长等问题😝
